<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
$_productCollection = $block->getLoadedProductCollection();
$helper_data = $this->helper('Ced\CsMarketplace\Helper\Data');
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$vendor = $this->getVendor();
?>
<h1><?= $vendor->getName() ?> &nbsp;<a href="/csvendorreview/rating/lists/id/<?= $vendor->getId() ?>/"><button class="btn btn-primary">View Reviews</button></a></h1>
<?php if($this->helper('Ced\CsMarketplace\Helper\Acl')->isEnabled()) { ?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div>You currently have no items for sale. Please visit our <a href="/sell">sell</a> page to begin listing items.</div>
    </div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php
            $iterator = 1;  // Vendor Logo
            $width = (int)$helper_data->getStoreConfig('ced_vshops/general/list_image_width', $this->getCurrentStoreId());
            $height = (int)$helper_data->getStoreConfig('ced_vshops/general/list_image_height', $this->getCurrentStoreId());
            $width = $width ? $width : 200;
            $height = $height ? $height : 200;
        ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                    </div>
                </div>
              <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
     <p>
        <?php echo $block->getToolbarHtml() ?>
    </p>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<?php } ?>

<style>
.page-title-wrapper {
  display: none;
}
@media (min-width: 575.98px) {.products.products-grid .products .product-item {margin-right: 2em;}}
.toolbar-amount {
  margin-top: 0.5em;
}
@media (max-width: 575.98px) {
  .account .page-main, .cms-privacy-policy .page-main {
    padding-top: 0;
  }
  .field.limiter {
    display: none;
  }
  .toolbar-amount {
    display: none;c
  }
  .page.messages {
    display: none;
  }
}
.sorter {
  margin-right: 7em;
}
.action.sorter-action.sort-asc{
  display: none;
}
.product-item-info {
  padding-bottom: 1.7em;
}
</style>
