<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
$_productCollection = $block->getLoadedProductCollection();
$helper_data = $this->helper('Ced\CsMarketplace\Helper\Data');
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$vendor = $this->getVendor();
$type = $this->getRequest()->getParam('type');
$customer_account = strpos($_SERVER['REQUEST_URI'], 'vendor_shop') === FALSE;

if($type != 'sold'){
  $type = 'for-sale';
}// end if
?>
<div class="col-md-8">
<?php
if($vendor != null){
?>
    <h1><?= $vendor->getName() ?> &nbsp;<a href="/csvendorreview/rating/lists/id/<?= $vendor->getId() ?>/"><button class="btn btn-primary">View Reviews</button></a></h1>
<?php
}// end if vendor is not null
?>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="control custom custom-button-group">
      <div class="ck-button <?= $type == 'for-sale' ? 'blue-background checked-button' : 'unchecked-button' ?> for-sale-button">
        <label style="cursor: pointer;">
          <input <?= $type == 'for-sale' ? 'checked' : '' ?> class="bought_sold" style="margin-left: 0.2em; margin-top: 0.3em;" type="radio" value="Y" name="bought_sold" id="for-sale"> <span style="margin-left: 1em; margin-right: 1.5em width: 100%">&nbsp;<strong>For Sale</strong></span>
        </label>
      </div>
      <div class="ck-button <?= $type == 'sold' ? 'blue-background checked-button' : 'unchecked-button' ?>">
        <label style="cursor: pointer;">
            <input <?= $type == 'sold' ? 'checked' : '' ?> class="bought_sold" style="margin-left: 0.2em; margin-top: 0.3em;" type="radio" value="Y" name="bought_sold" id="sold" /> <span style="margin-right: 1.5em; width: 100%; height: 100%;"> &nbsp;&nbsp;<strong>Sold</strong></span>
        </label>
      </div>
    </div>
  </div>
</div>
<br class="mobile-only" /><br class="mobile-only" />
<?php if($this->helper('Ced\CsMarketplace\Helper\Acl')->isEnabled()) { ?>
<?php if (!$_productCollection->count()): ?>
    <?php
      if($type == 'for-sale' && $vendor != null){
?>
    <div class="message info empty">
        <div><?= $vendor->getName() ?> has no items for sale.</div>
    </div>
<?php
      }else{
?>
    <div class="message info empty">
        <div>You currently have no items for sale. Please visit our <a href="/sell">sell</a> page to begin listing items.</div>
    </div>
<?php
      }
    ?>
<?php else: ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php
            $iterator = 1;  // Vendor Logo
            $width = (int)$helper_data->getStoreConfig('ced_vshops/general/list_image_width', $this->getCurrentStoreId());
            $height = (int)$helper_data->getStoreConfig('ced_vshops/general/list_image_height', $this->getCurrentStoreId());
            $width = $width ? $width : 200;
            $height = $height ? $height : 200;
        ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php
            $count = 0;
            ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php
                if(($type == 'sold' && empty($_product->getCategoryIds()) || ($type == 'for-sale' && !empty($_product->getCategoryIds())))){
                ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                    </div>
                </div>
                <?php
                $count++;
                }// end if display product
                ?>
              <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php
    if($type == 'sold' && $count == 0){
      if($vendor != null){
    ?>
    <div class="message info empty">
        <div><?= $vendor->getName() ?> has not sold any items.</div>
    </div>
    <?php
      }else {
    ?>
    <div class="message info empty">
        <div>You have not sold any items. Please visit our <a href="/sell">sell</a> page to begin listing items.</div>
    </div>
    <?php
      }
    }else if($type == 'for-sale' && $count == 0){
      // type for sale
      if($vendor != null){
    ?>
    <div class="message info empty">
        <div><?= $vendor->getName() ?> has no items for sale.</div>
    </div>
    <?php
      }else {
    ?>
    <div class="message info empty">
        <div>You have not sold any items. Please visit our <a href="/sell">sell</a> page to begin listing items.</div>
    </div>
  <?php
      }// end if vendor
    }// end if type sold and no products
      if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<?php } ?>

<style>
@media(min-width: 576px){
  .mobile-only {
    display: none;
  }
<?php
  if($customer_account){
?>
  .custom-button-group {
    margin-top: -4.5em !important;
    margin-left: -1em;
  }
<?php
}else{
?>
  .custom-button-group {
    margin-left: 1.2em;
  }
<?php
}// end if not vendor shop
?>
}
.ck-button {
  margin:4px;
  background-color:#EFEFEF;
  border-radius: 4px;
  border:1px solid #D0D0D0;
  overflow:auto;
  float:left;
  padding: 6px;
}

.ck-button:hover {
    background: #3CBBD8;
}

.ck-button label {
    float:left;
    width: 6.0em;
}

.ck-button label span {
    text-align:center;
    padding: 3px 0px 3px;
    display: block;
}

.ck-button label input {
    position:absolute;
}

.ck-button input:checked + span {
    color:#fff;
}
.blue-background {
  background: #3CBBD8;
}
@media (max-width: 575.98px) {
  .checked-button:hover {
    background: #3CBBD8 !important;
    color: white;
  }
  .ck-button {
    margin-top: -1em;
  }
  <?php
  if(!$customer_account){
?>
  .for-sale-button {
    margin-left: 1em;
  }
<?php
  }// end if customer account
  ?>
  .unchecked-button:hover {
    background-color: #EFEFEF !important;
    color: black;
  }
}
<?php
if(strpos($_SERVER['REQUEST_URI'], 'vendor_shop') !== FALSE){
 ?>
.page-title-wrapper {
  display: none;
}
<?php
}// end if vendor shop page
?>
@media (min-width: 575.98px) {
  .products.products-grid .products .product-item {
    margin-right: 1em;
    margin-left: 1em;
    margin-bottom: 0em;
  }
}
.toolbar-amount {
  margin-top: 0.5em;
}
@media (max-width: 575.98px) {
  .account .page-main, .cms-privacy-policy .page-main {
    padding-top: 0;
  }
  .field.limiter {
    display: none;
  }
  .toolbar-amount {
    display: none;c
  }
  .page.messages {
    display: none;
  }
}
.sorter {
  margin-right: 7em;
}
.action.sorter-action.sort-asc{
  display: none;
}
.product-item-info {
  padding-bottom: 1.7em;
}
</style>
<script>
require(['jquery'], ($) => {
   $('.bought_sold').click(function(){
     let checked = $(this).closest('.ck-button');
     checked.removeClass('unchecked-button');
     checked.addClass('blue-background').addClass('checked-button');

     let unchecked = $('.bought_sold:not(:checked)').closest('.ck-button');
     unchecked.removeClass('checked-button');
     unchecked.removeClass('blue-background').addClass('unchecked-button');
<?php
     $uri_parts = explode('?', $_SERVER['REQUEST_URI'], 2);
?>
     window.location = 'https://<?= $_SERVER['HTTP_HOST'] . $uri_parts[0] ?>?type=' + this.id;
   });
});
</script>
