<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$type = $this->getRequest()->getParam('type');

if($type != 'sold'){
  $type = 'bought';
}// end if
?>
<div class="col-md-8"></div>
<div class="col-md-4">
  <div class="control custom">
    <div class="ck-button <?= $type == 'bought' ? 'blue-background checked-button' : 'unchecked-button' ?>">
      <label style="cursor: pointer;">
        <input style="visibility: hidden" <?= $type == 'bought' ? 'checked' : '' ?> class="bought_sold" style="margin-left: 0.2em; margin-top: 0.3em;" type="radio" value="Y" name="bought_sold" id="bought"> <span style="margin-left: -0.3em; width: 100%">&nbsp;<strong>Bought</strong></span>
      </label>
    </div>
    <div class="ck-button <?= $type == 'sold' ? 'blue-background checked-button' : 'unchecked-button' ?>">
      <label style="cursor: pointer; width: 5em">
          <input style="visibility: hidden" <?= $type == 'sold' ? 'checked' : '' ?> class="bought_sold" style="margin-left: 0.2em; margin-top: 0.3em;" type="radio" value="Y" name="bought_sold" id="sold" /> <span style="margin-left: -0.3em; width: 100%; height: 100%;"> &nbsp;&nbsp;<strong>Sold</strong></span>
      </label>
    </div>
  </div>
</div><br class="mobile-only" /><br class="mobile-only" />
<?php $_orders = $block->getOrders(); ?>
<?php echo $block->getChildHtml('info');?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Orders') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Order #') ?></th>
                    <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Date') ?></th>
                    <?php /* @noEscape */ echo $block->getChildHtml('extra.column.header');?>
                    <th scope="col" class="col shipping"><?php /* @escapeNotVerified */ echo __($type == 'bought' ? 'Seller' : 'Buyer') ?></th>
                    <th scope="col" class="col shipping"><?php /* @escapeNotVerified */ echo __('Item Name') ?></th>
                    <th scope="col" class="col total"><?php /* @escapeNotVerified */ echo __('Total') ?></th>
                    <th scope="col" class="col actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order): ?>
                  <?php
                  if(isset($_GET['type']) && $_GET['type'] == 'sold'){
                    $_order = $_order->getOrder();
                  }else{
                    $order_number = $_order->getIncrementId();

                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                    $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
                    $connection = $resource->getConnection();

                    $sql = "SELECT vendor_id FROM ced_csmarketplace_vendor_sales_order WHERE order_id =  '".$this->escapeQuote($order_number)."'";
                    $result = $connection->fetchAll($sql); // gives associated array, table fields as key in array.

                    $vendor_id = $result[0]['vendor_id'];
                    $vendor = $objectManager->create('Ced\CsMarketplace\Model\Vendor')->load($vendor_id);
                  }// end if type sold

                  $items = $_order->getAllItems();
                  $product = $items[0]->getProduct();

                  ?>
                    <tr>
                        <td data-th="<?php echo $block->escapeHtml(__('Order #')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $_order->getRealOrderId() ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra): ?>
                            <?php $extra->setOrder($_order); ?>
                            <?php /* @noEscape */ echo $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <?php
                        if($type == 'bought'){
                        ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Seller')) ?>" class="col shipping"><?php echo $vendor->getName().'&nbsp;' ?></td>
                        <?php
                        }else{
                          // type sold
                          ?>
                          <td data-th="<?php echo $block->escapeHtml(__('Buyer')) ?>" class="col shipping"><?php echo $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                          <?php
                        }// end if type == 'bought'
                        ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Product')) ?>" class="col item"><?php echo $product->getName() ? $block->escapeHtml($product->getName()) : '&nbsp;' ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Total')) ?>" class="col total"><?php /* @escapeNotVerified */ echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                          <?php
                          if($type == 'bought'){
                          ?>
                            <a href="/review?id=<?= $_order->getId() ?>" class="action view">
                                <span><?php /* @escapeNotVerified */ echo __('Leave Review') ?></span>
                            </a>
                          <?php
                          }else{
                          ?>
                            <a href="/tracking?id=<?= $_order->getId() ?>" class="action view">
                                <span><?php /* @escapeNotVerified */ echo __('Enter Tracking') ?></span>
                            </a>
                          <?php
                          }// end if type == 'bought'
                          ?>
                            |

                            <a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order) ?>" class="action view">
                                <span><?php /* @escapeNotVerified */ echo __('View Order') ?></span>
                            </a>
                            <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
                                <a href="#" data-post='<?php /* @escapeNotVerified */ echo
                                $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                    ->getPostData($block->getReorderUrl($_order))
                                ?>' class="action order">
                                    <span><?php /* @escapeNotVerified */ echo __('Reorder') ?></span>
                                </a>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <br class="mobile-only" /><div class="message info empty"><span><?php /* @escapeNotVerified */ echo __($type == 'bought' ? 'You have not placed any orders.' : 'You have not sold any items. Please visit our <a href="/sell">sell</a> page to begin listing items.'); ?></span></div>
<?php endif ?>
<style>
.account .table-wrapper .action {
  margin-right: 0 !important;
}
@media(min-width: 576px){
  .mobile-only {
    display: none;
  }
  .actions {
    text-align: center;
  }
  .custom {
    float: right;
    margin-top: -4em;
  }
  .mobile-only {
    display: none;
  }
}
.limiter {
  display: none;
}
.action.back {
  display: none !important;
}
.ck-button {
  margin:4px;
  background-color:#EFEFEF;
  border-radius: 4px;
  border:1px solid #D0D0D0;
  overflow:auto;
  float:left;
  padding: 6px;
}

.ck-button:hover {
    background: #3CBBD8;
}

.ck-button label {
    float:left;
    width: 6.0em;
}

.ck-button label span {
    text-align:center;
    /* padding: 3px 0px 3px; */
    display: block;
}

.ck-button label input {
    position:absolute;
}

.ck-button input:checked + span {
    color:#fff;
}
.blue-background {
  background: #3CBBD8;
}
@media (max-width: 575.98px) {
  .checked-button:hover {
    background: #3CBBD8 !important;
    color: white;
  }
  .unchecked-button:hover {
    background-color: #EFEFEF !important;
    color: black;
  }
  .account .page-main, .cms-privacy-policy .page-main {
    padding-top: 0;
  }
  .account .page.messages {
    margin-bottom: 0;
  }
  .custom {
      margin-left: -1.3em
  }
}
</style>
<script>
require(['jquery'], ($) => {
   $('.bought_sold').click(function(){
     let checked = $(this).closest('.ck-button');
     checked.removeClass('unchecked-button');
     checked.addClass('blue-background').addClass('checked-button');

     let unchecked = $('.bought_sold:not(:checked)').closest('.ck-button');
     unchecked.removeClass('checked-button');
     unchecked.removeClass('blue-background').addClass('unchecked-button')
     window.location = 'https://<?= $_SERVER['HTTP_HOST'] ?>/sales/order/history?type=' + this.id;
   });
});
</script>
