<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
$_order = $block->getOrder();
$order_number = $_order->getIncrementId();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');

$sql = "SELECT vendor_id FROM ced_csmarketplace_vendor_sales_order WHERE order_id =  '".$this->escapeQuote($order_number)."'";
$result = $connection->fetchAll($sql); // gives associated array, table fields as key in array.

if(count($result) > 0 && $result[0]['vendor_id'] == $customerSession->getVendorId()){
  $type = 'sold';
}else{
  $type = 'bought';
}// end if

if(strpos($_SERVER['REQUEST_URI'], '/tracking') !== FALSE){
  $type = 'bought';
}// end if tracking

$totals = $block->getTotals();
$total = $totals['subtotal']->getValue();
?>
<?php foreach ($totals as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?php echo $block->getChildHtml($_total->getBlockName(), false); ?>
    <?php else:?>
<?php
    if($_code == 'grand_total' && ($block->isSellerEmail() || $type == 'sold')){
      $_total->setLabel('Your Profit');
      $num = $total - (($total * 0.099) + 0.3); 
      $_total->setValue(floor($num * 100) / 100);
    }
?>
    <tr class="<?php /* @escapeNotVerified */ echo $_code?>">
        <th <?php /* @escapeNotVerified */ echo $block->getLabelProperties()?> scope="row">
            <?php if ($_total->getStrong()):?>
            <strong><?php echo $block->escapeHtml($_total->getLabel());?></strong>
            <?php else:?>
            <?php echo $block->escapeHtml($_total->getLabel());?>
            <?php endif?>
        </th>
        <td <?php /* @escapeNotVerified */ echo $block->getValueProperties()?> data-th="<?php echo $block->escapeHtml($_total->getLabel());?>">
            <?php if ($_total->getStrong()):?>
            <strong><?php /* @escapeNotVerified */ echo $block->formatValue($_total) ?></strong>
            <?php else:?>
            <?php /* @escapeNotVerified */ echo $block->formatValue($_total) ?>
            <?php endif?>
        </td>
    </tr>
<?php
  if($_code == 'shipping' && $block->isSellerEmail()){
?>
  <tr>
    <th>Service Fee</th>
    <td colspan=2><?= money_format('$%i', ($total * 0.099) + 0.3) ?></td>
  </tr>
<?php
}else if($_code == 'shipping' && $type == 'sold'){
  $_total = $prev_total;
  $_total->setLabel('Service Fee');
  $_total->setValue(($total * 0.099) + 0.3);
?>
    <tr class="<?php /* @escapeNotVerified */ echo $_code?>">
        <th <?php /* @escapeNotVerified */ echo $block->getLabelProperties()?> scope="row">
            <?php if ($_total->getStrong()):?>
            <strong><?php echo $block->escapeHtml($_total->getLabel());?></strong>
            <?php else:?>
            <?php echo $block->escapeHtml($_total->getLabel());?>
            <?php endif?>
        </th>
        <td <?php /* @escapeNotVerified */ echo $block->getValueProperties()?> data-th="<?php echo $block->escapeHtml($_total->getLabel());?>">
            <?php if ($_total->getStrong()):?>
            <strong><?php /* @escapeNotVerified */ echo $block->formatValue($_total) ?></strong>
            <?php else:?>
            <?php /* @escapeNotVerified */ echo $block->formatValue($_total) ?>
            <?php endif?>
        </td>
    </tr>
<?php
}// end if shipping
?>
<?php
  $prev_total = $_total;
?>
    <?php endif?>
<?php endforeach?>
