<?php

/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category  Ced
  * @package   Ced_CsVendorReview
  * @author    CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license      http://cedcommerce.com/license-agreement.txt
  */
?>
<?php   $_items = $this->getReviews();
        $format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
        $_votes = $this->getRatings();
        $ob = \Magento\Framework\App\ObjectManager::getInstance();
        $msg = $ob->get('\Magento\Framework\Message\ManagerInterface');
        $messages = $msg->getMessages(true,"message_manager_example");
        $vendor = $this->getVendor();

        if($msg = $messages->getLastAddedMessage())
        {
        ?>
            <script>
                require(['mage/url','jquery'], function() {
                    jQuery('.messages').first().after('<div class="message-success success message"><div><?php echo $msg->getText()?></div></div>');
                });
            </script>
        <?php
        }
        $type = $this->getRequest()->getParam('type');
        if($type != 'submitted_reviews'){
          $type = 'my_reviews';
        }// end if
?>
<div class="col-md-6"></div>
<div class="col-md-6">
  <div class="control custom">
    <div class="ck-button my-reviews <?= $type == 'my_reviews' ? 'blue-background checked-button' : 'unchecked-button' ?>">
      <label style="cursor: pointer;">
        <input <?= $type == 'my_reviews' ? 'checked' : '' ?> class="review_type" style="margin-left: 0.2em; margin-top: 0.3em;" type="radio" value="Y" name="review_type" id="my_reviews"> <span style="margin-left: 0.3em; margin-right: 1.5em; width: 100%">&nbsp;<strong>My Reviews</strong></span>
      </label>
    </div>
    <div class="ck-button <?= $type == 'submitted_reviews' ? 'blue-background checked-button' : 'unchecked-button' ?>">
      <label style="cursor: pointer;">
          <input <?= $type == 'submitted_reviews' ? 'checked' : '' ?> class="review_type" style="margin-left: 0.2em; margin-top: 0.3em;" type="radio" value="Y" name="review_type" id="submitted_reviews" /> <span style="margin-right: 1.5em; width: 100%; height: 100%;"> &nbsp;&nbsp;<strong>Submitted Reviews</strong></span>
      </label>
    </div>
  </div>
</div>
<br class="mobile-only" /><br class="mobile-only" /><br class="mobile-only"/><br class="mobile-only" /><br class="mobile-only" /><br class="mobile-only" />
<?php
  if(count($_items) == 0){
?>
<?php
    if($type == 'submitted_reviews'){
?>
  <hr class="custom-hr" /><div class="message info empty">
      <div>You have not submitted any reviews yet.</div>
  </div>
    <?php
    }else{
?>
  <hr class="custom-hr" />
  <div class="message info empty">
      <div>You have no submitted reviews yet.</div>
  </div>
<?php
    }
?>
  <style>
  #horizontal-rule {
    display: none;
  }
  .block-content {
    padding-bottom: 0 !important;
  }
  @media(min-width: 586px){
    .custom {
      margin-top: -10em !important;
    }
  }
  </style>
<?php
}else{
?>
<div class="block review-list" id="customer-reviews">
    <div class="block-content">
        <!-- <div class="toolbar review-toolbar">
            <?php echo $block->getChildHtml('toolbar') ?>
        </div> -->
        <ol class="items review-items">
        <?php foreach ($_items as $_review):?>
            <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
                <div class="review-title" style="font-size: 0" itemprop="name"></span><br/>
                <span style="font-size: 16px"><?= $_review->getSubject() ?></span>

                </div>

                <?php if (count($_votes)): ?>
                    <div class="review-ratings">
                    <?php foreach ($_votes as $_vote): ?>
                     <?php if($_review[$_vote->getRatingCode()]!=''): ?>
                    <div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                        <span class="label rating-label"><span><?php echo $_vote->getRatingLabel() ?></span></span>
                        <div class="rating-result" title="<?php echo $_review[$_vote->getRatingCode()] ?>%">
                            <meta itemprop="worstRating" content = "1"/>
                            <meta itemprop="bestRating" content = "100"/>
                            <span style="width:<?php echo $_review[$_vote->getRatingCode()] ?>%;">
                                <span><?php echo $_review[$_vote->getRatingCode()] ?>%</span>
                            </span>
                        </div>
                    </div>
                    <?php endif;?>
                    <?php endforeach; ?>
                    </div>
                <?php endif; ?>
                <div class="review-content" itemprop="description">
                    <?php echo nl2br($_review->getReview()) ?>
                </div>
                <div class="review-details">
                    <p class="review-author">
                        <span class="review-details-label"><?php /* @escapeNotVerified */ echo __('Review by')?></span>
                        <strong class="review-details-value" itemprop="author"><?php echo $_review->getCustomerName(); ?></strong>
                    </p>
                    <p class="review-date">
                        <span class="review-details-label"><?php /* @escapeNotVerified */ echo __('Posted on') ?></span>
                        <time class="review-details-value" itemprop="datePublished" datetime="<?php echo $block->formatDate($_review->getCreatedAt(), $format)  ?>"><?php echo $block->formatDate($_review->getCreatedAt(), $format)  ?></time>
                    </p>
                </div>
            </li>
        <?php endforeach; ?>
        </ol>
        <div class="toolbar review-toolbar">
            <?php echo $block->getChildHtml('toolbar') ?>
        </div>
    </div>
</div>
<?php
  }// end if count == 0
?>
<style>
@media(min-width: 576px){
  .custom {
    float: right;
    margin-top: -11em;
  }
  .mobile-only {
    display: none;
  }
  .custom-hr {
    margin-top: 28px !important;
  }
}
.review-item {
  padding-top: 0;
}
.review-title {
  margin-top: 20px !important;
  margin-bottom: 15px !important;
}
.ck-button {
  margin:4px;
  background-color:#EFEFEF;
  border-radius: 4px;
  border:1px solid #D0D0D0;
  overflow:auto;
  float:left;
  padding: 6px;
}

.ck-button:hover {
    background: #3CBBD8;
}

.ck-button label {
    float:left;
    width: 12.3em;
}
.ck-button.my-reviews label {
    width: 9em !important;
}

.ck-button label span {
    text-align:center;
    padding: 3px 0px 3px;
    display: block;
}

.ck-button label input {
    position:absolute;
}

.ck-button input:checked + span {
    color:#fff;
}
.blue-background {
  background: #3CBBD8;
}
@media (max-width: 575.98px) {
  .account .page.messages {
    margin-bottom: 1em;
  }
  .page-title {
    margin-bottom: 0 !important;
  }
  .checked-button:hover {
    background: #3CBBD8 !important;
    color: white;
  }
  .unchecked-button:hover {
    background-color: #EFEFEF !important;
    color: black;
  }
  .account .page-main, .cms-privacy-policy .page-main{
    padding-top: 0
  }
  .custom {
      margin-left: -1.3em
  }
  .custom-hr {
    margin-top: 0 !important;
  }
}
</style>
<script>
require(['jquery'], ($) => {
   $('.review_type').click(function(){
     let checked = $(this).closest('.ck-button');
     checked.removeClass('unchecked-button');
     checked.addClass('blue-background').addClass('checked-button');

     let unchecked = $('.bought_sold:not(:checked)').closest('.ck-button');
     unchecked.removeClass('checked-button');
     unchecked.removeClass('blue-background').addClass('unchecked-button')
     window.location = 'https://<?= $_SERVER['HTTP_HOST'] ?>/review/customer?type=' + this.id;
   });
});
</script>
