<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * New Customer block template
 *
 * @var \Magento\Customer\Block\Form\Login\Info $block
 */

$referer = $_SERVER['HTTP_REFERER'];

if(isset($_SESSION['from_sell_form']) && $_SESSION['from_sell_form']){
  $referer = 'https://'.$_SERVER['HTTP_HOST'].'/sell';
  $_SESSION['from_sell_form'] = false;
}
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
    <div class="block-title">
        <strong id="block-new-customer-heading" role="heading" aria-level="2"><?php echo $block->escapeHtml(__('New Users')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <p><?php echo $block->escapeHtml(__('Creating an account has many benefits: start selling items, check out faster, manage messages and offers, easy access to Stripe, and much more.')) ?></p>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?php echo rtrim($block->escapeUrl($block->getCreateAccountUrl()), '/') ?>?referer=<?php echo urlencode($referer) ?>" class="action create primary"><span><?php echo $block->escapeHtml(__('Create an Account')) ?></span></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
