<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMessaging
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

?>
<style>

    .form-group {
        width: 103%;
    }

</style>
<?php

$product_id = $this->getRequest()->getParam('product_id');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->create('Magento\Catalog\Model\Product')->load($product_id);
$vendor_id = $this->getRequest()->getParam('vendor_id');
$subject = $this->getRequest()->getParam('subject');
$customer_id = $this->getRequest()->getParam('id');
$customer = $this->_customerRepositoryInterface->getById($customer_id);
$customerName = $customer->getFirstName() . " " . $customer->getLastName();

$vendor = $this->_vendorFactory->load($vendor_id);
$vendor_email = $vendor->getEmail();
$messages = $this->getCollection();
$vendors = $this->_vendorFactory->getCollection()->getData();
$admin_name = $this->_scopeConfig->getValue('trans_email/ident_general/name', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
//$vendors[] = ['entity_id'=> 0,'name'=>$admin_name];
$adminInboxCount = $this->_messagingHelper->getCustomerInboxCountForAdmin();
$vendorInboxCount = $this->_messagingHelper->getCustomerInboxCountForVendor();
?>

<div class="top_msg"></div>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="left-sidebar-wrap">
                <div class="box-header with-border box-folder">
                    <h3 class="box-title"><?php echo __('Folders') ?></h3>
                </div>
                <div class="box box-solid">

                    <div class="box-body no-padding">
                        <ul class="nav nav-pills nav-stacked">
                            <li><a
                                        href="<?php echo $this->getUrl('csmessaging/frontend/inbox');//Mage::getUrl('csvendorchat/frontend/inbox')?>"
                                        class="fa fa-inbox"><?php echo __(' Inbox'); ?> <span
                                            class="label label-primary pull-right"><?php if ($vendorInboxCount > 0) {
                                            echo '(';
                                            echo $vendorInboxCount;
                                            echo ')';
                                        } ?></span></a></li>
                            <li><a
                                        href="<?php echo $this->getUrl('csmessaging/frontend/sent');//Mage::getUrl('csvendorchat/frontend/sent')?>"
                                        class="sent-mail-tab fa fa-envelope-o"> Sent</a></li>

                        </ul>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
            <!-- /.col -->
            <div class="right-sidebar-wrap mail-compose">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Reply to <?= $customerName ?></h3>
                        <div class="clear"></div>
                    </div>
                    <!-- /.box-header -->
                    <form method="post"
                          action="<?php echo $this->getUrl();//Mage::getBaseUrl()?>csmessaging/frontend/savechat"
                          enctype="multipart/form-data">
                          <input type="hidden" name="sent_to_vendor" value="1" />
                          <input type="hidden" name="reply" value="1" />
                          <input type="hidden" value="<?php echo $customer->getId() ?>" name="vendor_id" />
                          <input type="hidden" name="email_subject" value="<?= $subject ?>" />
                          <input type="hidden" name="product_id" value="<?= $product_id ?>" />
                        <div class="table responsive">
                          <table class="table">
                            <tr>
                              <td>Item:</td>
                              <td><strong><a href="<?= $product->getProductUrl() ?>"><?= $subject ?></a></strong></td>
                            </tr>

                          </table>
                        </div>
                        <div class="form-group">
                          <label>Message:</label>
                            <textarea id="compose-textarea" name="text_email" class="form-control"
                                      style="height: 200px;width:97%;" value=""></textarea>
                        </div>
                        <div class="box-footer">
                            <a target="_blank" href="<?= $product->getProductUrl() ?>">View this Listing</a>
                            <div class="pull-right">
                                <button class="btn btn-primary" id="btn-chat" type="button" onclick="send()">
                                    <i class="fa fa-envelope-o"> <?php echo __('Send') ?></i>
                                </button>
                            </div>

                        </div>
                        <!-- /.box-footer -->
                    </form>
                </div>
                <!-- /.col -->
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
            <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

<style>
.right-sidebar-wrap {
  padding-left: 0px;
}
table > thead > tr > th, table > tbody > tr > th, table > tfoot > tr > th, table > thead > tr > td, table > tbody > tr > td, table > tfoot > tr > td {
  padding-left: 0px;
}
</style>
<script>
require([
    "jquery",
], ($) => {

  $(document).ready(function(){
    $('li:contains("Messages")').addClass('current');
  });
});
    function send() {
        var text = jQuery("#compose-textarea").val();
        var vendor_subject = jQuery("#vendor_subject").val();
        var vendorremail = jQuery("#vendor_data").val();
        var vendorId = '<?php echo $vendor_id; ?>';
        if (!text) {
            alert('Message cannot be Empty');
        }else {
            var btn = document.getElementById('btn-chat');
            btn.setAttribute('type', 'submit');
        }
    }
</script>
