<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMessaging
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

?>
<style>

    .form-group {
        width: 103%;
    }

</style>
<?php

$product_id = $this->getRequest()->getParam('product_id');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->create('Magento\Catalog\Model\Product')->load($product_id);
$vendor_id = $this->getRequest()->getParam('vendor_id');
$subject = $this->getRequest()->getParam('subject');
$customer_id = $this->getRequest()->getParam('id');
$customer = $this->_customerRepositoryInterface->getById($customer_id);
$customerName = $customer->getFirstName() . " " . $customer->getLastName();

$vendor = $this->_vendorFactory->load($vendor_id);
$vendor_email = $vendor->getEmail();
$messages = $this->getCollection();
$vendors = $this->_vendorFactory->getCollection()->getData();
$admin_name = $this->_scopeConfig->getValue('trans_email/ident_general/name', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
//$vendors[] = ['entity_id'=> 0,'name'=>$admin_name];
$adminInboxCount = $this->_messagingHelper->getCustomerInboxCountForAdmin();
$vendorInboxCount = $this->_messagingHelper->getCustomerInboxCountForVendor();
?>

<div class="top_msg"></div>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="left-sidebar-wrap">
                <div class="box-header with-border box-folder">
                    <h3 class="box-title"><?php echo __('Folders') ?></h3>
                </div>
                <div class="box box-solid">

                    <div class="box-body no-padding">
                        <ul class="nav nav-pills nav-stacked">
                            <li class="active"><a
                                        href="<?php echo $this->getUrl('csmessaging/frontend/inbox');//Mage::getUrl('csvendorchat/frontend/inbox')?>">
                                        <i class="fa fa-inbox"></i><?php echo __(' Inbox'); ?> <span
                                            class="label label-primary pull-right"><?php if ($vendorInboxCount > 0) {
                                            echo '(';
                                            echo $vendorInboxCount;
                                            echo ')';
                                        } ?></span></a></li>
                            <li><a
                                        href="<?php echo $this->getUrl('csmessaging/frontend/sent');//Mage::getUrl('csvendorchat/frontend/sent')?>">
                                        <i class="sent-mail-tab fa fa-envelope-o"></i> Sent</a></li>

                        </ul>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
            <!-- /.col -->
            <div class="right-sidebar-wrap mail-compose">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Reply to <?= $customerName ?></h3>
                        <div class="clear"></div>
                    </div>
                    <!-- /.box-header -->
                    <form method="post"
                          action="<?php echo $this->getUrl();//Mage::getBaseUrl()?>csmessaging/frontend/savechat"
                          enctype="multipart/form-data">
                          <input type="hidden" name="sent_to_vendor" value="1" />
                          <input type="hidden" name="reply" value="1" />
                          <input type="hidden" value="<?php echo $customer->getId() ?>" name="vendor_id" />
                          <input type="hidden" name="email_subject" value="<?= $subject ?>" />
                          <input type="hidden" name="product_id" value="<?= $product_id ?>" />
                        <div class="row">
                          <div class="col-xs-2">
                            Item:
                          </div>
                          <div class="col-xs-4">
                            <strong><a target="_blank" href="<?= $product->getProductUrl() ?>"><?= $subject ?></a></strong>
                          </div>
                          <div class="col-xs-6">
                            <button style="float: right;" class="btn btn-primary" onclick="window.open('<?= $product->getProductUrl() ?>', '_blank'); return false;">View Listing</button>
                          </div>
                        </div>
                        <div class="row" style="margin-bottom: 1em;">
                          <div class="col-md-3">
                            <div class="ck-button-wrapper">
                              <div class="ck-button">
                                <label style="cursor: pointer;">
                                  <input class="is_offer" style="margin-left: 0.2em; margin-top: 0.3em;" type="checkbox" name="is_offer" id="is_offer" value="Y" /> <span style="margin-right: 1.5em; width: 100%">&nbsp;<strong>Offer</strong></span>
                                </label>
                              </div>
                            </div>
                          </div>
                          <div class="offer-info" style="display: none">
                            <div class="col-md-3" style="margin-top: 1.1em;">
                              Price: <strong>$<?= trim(money_format('%(#10n', $product->getPrice())) ?></strong>
                            </div>
                            <div class="col-md-6" style="margin-top: 0.8em;">
                              <div class="row">
                                <div class="col-xs-5 offer-price-text" style="margin-top: 0.3em;">
                                  Offer Price ($):
                                </div>
                                <div class="col-xs-4">
                                  <input type="number" name="offer_price" id="offer-price" step="1" />
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="form-group">
                          <label>Message:</label>
                            <textarea id="compose-textarea" name="text_email" class="form-control" style="height: 200px;width:97%;" value=""></textarea>
                        </div>
                        <div class="box-footer">
                            <button class="btn btn-primary" onClick="history.go(-1);return false;"><span></span><<</span>Back</button>
                            <div class="pull-right">
                                <button class="btn btn-primary" id="btn-chat" type="button" onclick="send()">
                                    <i class="fa fa-envelope-o"></i> <?php echo __('Send') ?>
                                </button>
                            </div>
                        </div>
                        <!-- /.box-footer -->
                    </form>
                </div>
                <!-- /.col -->
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
            <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

<style>
.ck-button {
    margin:4px;
    background-color:#EFEFEF;
    border-radius: 4px;
    border:1px solid #D0D0D0;
    overflow:auto;
    float:left;
    padding: 6px;
}

.ck-button:hover {
    background: #3CBBD8;
}

.ck-button label {
    float:left;
    width: 6.0em;
}

.ck-button label span {
    text-align:center;
    padding: 3px 0px 3px;
    display: block;
}

.ck-button label input {
    position:absolute;
}

.ck-button input:checked + span {
    color:#fff;
}
.right-sidebar-wrap {
  padding-left: 0px;
}
.blue-background {
  background: #3CBBD8;
}
table > thead > tr > th, table > tbody > tr > th, table > tfoot > tr > th, table > thead > tr > td, table > tbody > tr > td, table > tfoot > tr > td {
  padding-left: 0px;
}

@media(max-width: 578px){
  .page-main {
    padding-top: 0px !important;
  }
  .ck-button {
    width: 30%;
    margin-right: 20em;
  }
}
@media(min-width: 578px){
  .offer-price-text {
    width: 35% !important;
  }
}
</style>
<script>
require([
    "jquery",
], ($) => {
  $('.is_offer').on('click touch', function(){
    $('.offer-info').toggle();
    let checkbutton = $(this).closest('.ck-button');
    checkbutton.toggleClass('blue-background');
  });
  $(document).ready(function(){
    $('li:contains("Messages")').addClass('current');
  });
});
    function send() {
        var $ = jQuery;
        var text = $("#compose-textarea").val();
        var vendor_subject = $("#vendor_subject").val();
        var vendorremail = $("#vendor_data").val();
        var vendorId = '<?php echo $vendor_id; ?>';
        var is_offer = document.getElementById('is_offer').checked;
        if (!text) {
            alert('Message cannot be empty.');
        }else if(is_offer){
          var offer_price = $('#offer-price').val();
          if(offer_price.trim() == ''){
            alert("Offer price cannot be empty.");
          }else if(isNaN(offer_price) || offer_price % 1 != 0 ){
            alert("Offer price must be a whole number.");
          }else if(offer_price < <?= $product->getPrice() * 0.75 ?>){
            let min_price = <?= $product->getPrice() ?> * 0.75;
            alert(`Offer price must be greater than or equal to $${min_price.toFixed(2)}`);
          }else{
            var btn = document.getElementById('btn-chat');
            btn.setAttribute('type', 'submit');
          }
        }else {
            var btn = document.getElementById('btn-chat');
            btn.setAttribute('type', 'submit');
        }
    }
</script>
