<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMessaging
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<?php
$collection = $block->getCollection();
$messages = $block->getinboxcollection();
$adminInboxCount = $this->_messagingHelper->getCustomerInboxCountForAdmin();
$vendorInboxCount = $this->_messagingHelper->getCustomerInboxCountForVendor();
?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="left-sidebar-wrap">
                <div class="box-header with-border box-folder">
                    <h3 class="box-title">Folders</h3>
                </div>

                <div class="box box-solid">
                    <div class="box-body no-padding">
                        <ul class="nav nav-pills nav-stacked">
                            <!-- <li>
                                <a href="<?php echo $this->getUrl('csmessaging/frontend/customercompose'); ?>"
                                   class="btn btn-block margin-bottom compose-tab"><?php echo __('Compose') ?></a>
                            </li> -->
                            <li class="active"><a
                                        class="fa fa-inbox" href="<?php echo $this->getUrl('csmessaging/frontend/inbox'); ?>"><?php echo __(' Inbox'); ?>
                                    <span class="label label-primary pull-right"><?php if ($vendorInboxCount > 0) {
                                            echo '(';
                                            echo $vendorInboxCount;
                                            echo ')';
                                        } ?></span></a></li>
                            <li><a href="<?php echo $this->getUrl('csmessaging/frontend/sent'); ?>"
                                   class="sent-mail-tab fa fa-envelope-o"> Sent</a></li>
                        </ul>
                    </div>
                </div>
            </div><!-- /.col -->
            <div class="right-sidebar-wrap mail-inbox">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Inbox</h3>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="box-body no-padding">
                    <div class="mailbox-controls">

                    </div><!-- /.pull-right -->
                </div>
                <?php if (!$collection->count()): ?>
                    <p class="note-msg"><?php echo __('There are no messages in your Inbox.') ?></p>
                <?php else: ?>
                    <div class="table-responsive mailbox-messages">
                        <table class="table table-hover table-striped">
                            <tbody>
                            <?php if (!empty($collection)): ?>
                                <?php foreach ($collection as $msg => $value): ?>
                                    <?php
                                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                    $sender = $objectManager->get('\Magento\Customer\Api\CustomerRepositoryInterface')->get($value['sender_email']);
                                    $vendor_name = $sender->getFirstName() . ' ' . $sender->getLastName();
                                    ?>
                                    <tr>
                                        <td class="mailbox-name">
                                          <a href="<?php echo $this->getUrl();//Mage::getBaseUrl()?>csmessaging/frontend/read?id=<?php echo $value['chat_id'] ?>"><?php echo ucwords($vendor_name) ?></a>
                                        </td>
                                        <td class="mailbox-subject"><b><a href="<?php echo $this->getUrl();//Mage::getBaseUrl()?>csmessaging/frontend/read?id=<?php echo $value['chat_id'] ?>"><?php echo $value['subject'] ?></a></td>
                                        <td class="mailbox-subject"></b><a href="<?php echo $this->getUrl();//Mage::getBaseUrl()?>csmessaging/frontend/read?id=<?php echo $value['chat_id'] ?>"><?php echo substr($value['message'], 0, 16); ?></a>
                                      <?php
                                        if(count($value['message']) > 16){
                                          echo '...';
                                        }
                                       ?>
                                        </td>
                                        <td class="mailbox-attachment"></td>
                                        <td class="mailbox-date"><a href="<?php echo $this->getUrl();//Mage::getBaseUrl()?>csmessaging/frontend/read?id=<?php echo $value['chat_id'] ?>"><?php echo date("F d, Y g:i A", strtotime($value['time']))
                                            ?></a></td>
                                    </tr>
                                    <?php
                                endforeach; ?>
                            <?php endif; ?>
                            </tbody>
                        </table><!-- /.table -->
                    </div><!-- /.mail-box-messages -->
                <?php endif; ?>
            </div><!-- /.box-body -->
            <div class="clear"></div>
            <div class="box-footer no-padding">
                <div class="mailbox-controls">

                </div><!-- /.pull-right -->
            </div>
        </div>
        <center>
            <?php echo $block->getPagerHtml(); ?> <!-- this is render next prev link -->
        </center>
</div>
