
<?php $chat_id = $this->getRequest()->getParam('id');
$chat = $this->_messagingFactory->create()->load($chat_id);
$product_id = $chat->getData('product_id');
$offer_price = $chat->getData('offer_price');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->create('Magento\Catalog\Model\Product')->load($product_id);

// determine if this is the seller
$vendorProduct = $objectManager->create('Ced\CsMarketplace\Model\Vproducts')->getCollection()->addFieldToFilter('sku', $product->getSku())->addFieldToFilter('check_status',['nin'=>3])->getFirstItem();
$vendorId = $vendorProduct->getVendorId();
$customerVendorId = $this->getSession()->getVendorId();
$is_seller = $vendorId == $customerVendorId;

$originalDate = $chat->getTime();
$newDate = date("F d, Y g:i A", strtotime($originalDate));
$messages = $this->getinboxcollection();
$adminInboxCount = $this->_messagingHelper->getCustomerInboxCountForAdmin();
$vendorInboxCount = $this->_messagingHelper->getCustomerInboxCountForVendor();

// get sender data
$sentMessage = $chat->getSenderId() == $this->getCustomer()->getId();

if($sentMessage){
  $sender = $this->getCustomerById($chat->getVendorId());
}else{
  $sender = $this->getCustomerById($chat->getSenderId());
}

$raw_offer_price = $offer_price;
if($offer_price != null){
  $offer_price = trim(money_format('%(#10n', $offer_price));
}
$formatted_price = trim(money_format('%(#10n', $product->getPrice()));
?>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="left-sidebar-wrap">
                <div class="box-header with-border box-folder">
                    <h3 class="box-title">Folders</h3>
                </div>

                <div class="box box-solid">

                    <div class="box-body no-padding">
                        <ul class="nav nav-pills nav-stacked">
                            <li <?= !$sentMessage ? "class='active'" : '' ?>>
                                <a href="<?php echo $this->getUrl('csmessaging/frontend/inbox');//Mage::getUrl('csvendorchat/frontend/inbox')?>"><i
                                            class="fa fa-inbox"></i><?php echo __(' Inbox'); ?> <span
                                            class="label label-primary pull-right"><?php if ($vendorInboxCount > 0) {
                                            echo '(';
                                            echo $vendorInboxCount;
                                            echo ')';
                                        } ?></span></a></li>
                            <li <?= $sentMessage ? "class='active'" : '' ?>>
                                <a href="<?php echo $this->getUrl('csmessaging/frontend/sent');//Mage::getUrl('csvendorchat/frontend/sent')?>"><i
                                            class="fa fa-envelope-o"></i> Sent</a></li>
                            <!--   <li><a href="#"><i class="fa fa-file-text-o"></i> Drafts</a></li>
                              <li><a href="#"><i class="fa fa-filter"></i> Junk <span class="label label-waring pull-right">65</span></a></li>
                              <li><a href="#"><i class="fa fa-trash-o"></i> Trash</a></li> -->
                        </ul>
                    </div><!-- /.box-body -->
                </div>
            </div><!-- /.col -->
            <div class="right-sidebar-wrap mail-read">
                <div class="box box-primary">
                    <div class="box-header with-border">
                      <?php
                      if($sentMessage && $offer_price != null){
?>
                        <h3 class="box-title">$<?= $offer_price ?> Offer Sent To <?= $sender->getFirstName() ." ".$sender->getLastName() ?></h3>
<?php
                      }else if($sentMessage){
?>
                        <h3 class="box-title">Sent To <?= $sender->getFirstName() ." ".$sender->getLastName() ?></h3>
<?php
                      }else if($offer_price != null){
?>
                        <h3 class="box-title">$<?= $offer_price ?> Offer From <?= $sender->getFirstName() ." ".$sender->getLastName() ?></h3>
<?php
                      }else{
?>
                        <h3 class="box-title">Message From <?= $sender->getFirstName() ." ".$sender->getLastName() ?></h3>
<?php
                      }// end if sent message
                       ?>
                      <div class="clear"></div>
                    </div>
                    <div class="box-body no-padding">
                        <div class="mailbox-read-info" style="padding-top: 0.2em; padding-left: 3px; max-height: 3.3em; padding-bottom: 0.5em;">
                          <div class="row">
                            <div class="col-xs-8">
                              <a target="_blank" href="<?= $product->getProductUrl() ?>">
                                <h3><?php echo $chat->getSubject(); ?>
                              </a>
                            </h3>
                          </div>
                            <div class="col-xs-4" style="float: right">
                              <a style="float: right; margin-left: 0.5em; margin-bottom: 0.5em;" class="btn btn-box-tool action subscribe primary"
                               onClick="history.go(-1);return true;"><span></span><<</span>Back</a>
<?php
                          if(!$sentMessage){
?>
                            <a style="float: right" class="btn btn-box-tool action subscribe primary"
                               href="<?php echo $this->getUrl(); ?>csmessaging/frontend/customercompose?id=<?php echo $chat->getSenderId() ?>&product_id=<?= $product_id ?>&subject=<?= urlencode($chat->getSubject()) ?>&vendor_id=<?= $chat->getVendorId() ?>">Reply</a>
<?php
                          }// end if not a sent
?>
                            </div>
                          </div>
                        </div>
                        </div><!-- /.mailbox-read-info -->
                        <!-- /.mailbox-controls -->
                        <div class="mailbox-read-message" style="padding-left: 5px;">
                            <?php echo $chat->getMessage() ?>
                        </div>  <!-- /.mailbox-read-message -->
                    </div><!-- /.box-body -->
                    <div class="box-footer" style="margin-top: 1em;">
                      <div class="row" >
                        <div class="col-xs-4" style="margin-top: 0.5em; padding-left: 5px; padding-right: 0px;">
                          <div class="mailbox-read-time" style="margin-left: 1em;"><?php echo $newDate; ?></div>
                        </div>
                          <div class="col-xs-8">
                            <div style="float: right;">
  <?php
                            if(!$sentMessage && $offer_price != null){
   ?>
                                <a style="margin-top: 0.3em; cursor: pointer;"  id="accept_offer" class="btn btn-box-tool action subscribe primary mobile-right">Accept</a>
                                <a href="<?php echo $this->getUrl(); ?>csmessaging/frontend/customercompose?id=<?php echo $chat->getSenderId() ?>&product_id=<?= $product_id ?>&subject=<?= urlencode($chat->getSubject()) ?>&vendor_id=<?= $chat->getVendorId() ?>&counter=true" style="margin-top: 0.3em;" class="btn btn-box-tool action subscribe primary mobile-right">Counter Offer</a>
  <?php
                            }// end if offer
  ?>
                             <a style="margin-top: 0.3em;" target="_blank" class="btn btn-box-tool action subscribe primary mobile-right" href="<?= $product->getProductUrl() ?>">View Listing</a>
                           </div>
                          </div>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </section>
    <div style="display: none" id="accept-offer-modal">
      <form id="message-form" action="/csmessaging/frontend/savechat" method="POST"></form>
        <div class="row" style="margin-bottom: 1em">
          <div class="col-md-12" style="margin-left: 1em;">
            <p>Are you sure you want to accept this offer?</p><br/>
            <p>This will update your listing price from <strong>$<?= $formatted_price ?></strong> to <strong>$<?= $offer_price ?>.</strong></p>
          </div>
        </div>
      </form>
    </div>
<style>
.page-wrapper {
  min-height: 87%;
}
.right-sidebar-wrap{
  padding-left: 0px;
}
.columns::after {
  clear: none;
}
@media(max-width: 578px){
  .mailbox-read-time{
    font-size: 12px;
  }
  .modal-popup.modal-slide._inner-scroll .modal-inner-wrap {
      height: auto;
      width: 100% !important;
      min-height: 100%;
  }
  .modal-footer {
    padding-bottom: 0 !important;
    margin-top: 0 !important;
  }
  .modal-content {
    padding-bottom: 0 !important;
  }
  .mobile-right {
    float: right;
  }
  .page-main {
    padding-top: 0px !important;
  }
}
@media(min-width: 578px){
  .desktop-full {
    width: 100% !important;
  }
  .mobile-break {
    display: none;
  }
}
</style>

<script>
require([
    "jquery",
    'Magento_Ui/js/modal/modal'
], ($, modal) => {
  $('#accept_offer').click(() => {
<?php
  if($is_seller){
?>
  var acceptOptions = {
    type: 'popup',
    responsive: true,
    innerScroll: true,
    title: 'Accept Offer - <?= $product->getName() ?>',
    buttons: [{
      text: $.mage.__('Accept'),
      class: 'accept-button',
      click: function () {
        let offer_price = '<?= $raw_offer_price ?>';
        let product_id = '<?= $product_id ?>';
        let receiver_id = '<?= $sender->getId() ?>';
        $.post('/api/product/acceptoffer', { offer_price, product_id, receiver_id }, (response) => {
            for(key in response){
              $('<input>').attr({
                  type: 'hidden',
                  name: key,
                  value: response[key]
              }).appendTo('#message-form');
            }// end loop over response
            $('#message-form').submit();
          });
      }// end click function
    }]
  };
  var popup = modal(acceptOptions, $('#accept-offer-modal'));
  $('#accept-offer-modal').modal('openModal');
<?php
  }else{
?>
  window.location = '<?= $product->getProductUrl() ?>';
<?php
  }// end if is seller
?>
  });
  $(document).ready(function(){
<?php
  if(isset($_GET['accept_confirm']) && $_GET['accept_confirm'] == 'true'){
?>
  $('#accept_offer').click();
<?php
  }// end if accept confirm
 ?>
    $('li:contains("Messages")').addClass('current');
  });
});
</script>
