
<?php $chat_id = $this->getRequest()->getParam('id');
$chat = $this->_messagingFactory->create()->load($chat_id);
$product_id = $chat->getData('product_id');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->create('Magento\Catalog\Model\Product')->load($product_id);

$originalDate = $chat->getTime();
$newDate = date("F d, Y g:i A", strtotime($originalDate));
$messages = $this->getinboxcollection();
$adminInboxCount = $this->_messagingHelper->getCustomerInboxCountForAdmin();
$vendorInboxCount = $this->_messagingHelper->getCustomerInboxCountForVendor();

// get sender data
$sentMessage = $chat->getSenderId() == $this->getCustomer()->getId();

if($sentMessage){
  $sender = $this->getCustomerById($chat->getVendorId());
}else{
  $sender = $this->getCustomerById($chat->getSenderId());
}

?>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="left-sidebar-wrap">
                <div class="box-header with-border box-folder">
                    <h3 class="box-title">Folders</h3>
                </div>

                <div class="box box-solid">

                    <div class="box-body no-padding">
                        <ul class="nav nav-pills nav-stacked">
                            <li <?= !$sentMessage ? "class='active'" : '' ?>>
                                <a href="<?php echo $this->getUrl('csmessaging/frontend/inbox');//Mage::getUrl('csvendorchat/frontend/inbox')?>"><i
                                            class="fa fa-inbox"></i><?php echo __(' Inbox'); ?> <span
                                            class="label label-primary pull-right"><?php if ($vendorInboxCount > 0) {
                                            echo '(';
                                            echo $vendorInboxCount;
                                            echo ')';
                                        } ?></span></a></li>
                            <li <?= $sentMessage ? "class='active'" : '' ?>>
                                <a href="<?php echo $this->getUrl('csmessaging/frontend/sent');//Mage::getUrl('csvendorchat/frontend/sent')?>"><i
                                            class="fa fa-envelope-o"></i> Sent</a></li>
                            <!--   <li><a href="#"><i class="fa fa-file-text-o"></i> Drafts</a></li>
                              <li><a href="#"><i class="fa fa-filter"></i> Junk <span class="label label-waring pull-right">65</span></a></li>
                              <li><a href="#"><i class="fa fa-trash-o"></i> Trash</a></li> -->
                        </ul>
                    </div><!-- /.box-body -->
                </div>
            </div><!-- /.col -->
            <div class="right-sidebar-wrap mail-read">
                <div class="box box-primary">
                    <div class="box-header with-border">
                      <?php
                      if($sentMessage){
?>
                        <h3 class="box-title">Sent To <?= $sender->getFirstName() ." ".$sender->getLastName() ?></h3>
<?php
                      }else{
?>
                        <h3 class="box-title">Message From <?= $sender->getFirstName() ." ".$sender->getLastName() ?></h3>
<?php
                      }// end if sent message
                       ?>
                      <div class="clear"></div>
                    </div>
                    <div class="box-body no-padding">
                        <div class="mailbox-read-info" style="padding-top: 0.2em; padding-left: 3px; max-height: 3.3em; padding-bottom: 0.5em;">
                          <div class="row">
                            <div class="col-xs-6">
                              <a target="_blank" href="<?= $product->getProductUrl() ?>">
                                <h3><?php echo $chat->getSubject(); ?>
                              </a>
                            </h3>
                          </div>
                            <div class="col-xs-6">
                              <a style="float: right" class="btn btn-box-tool action subscribe primary"
                               onClick="history.go(-1);return true;"><span></span><<</span>Back</a>
                            </div>
                          </div>
                        </div>
                        </div><!-- /.mailbox-read-info -->
                        <!-- /.mailbox-controls -->
                        <div class="mailbox-read-message" style="padding-left: 5px;">
                            <?php echo $chat->getMessage() ?>
                        </div>  <!-- /.mailbox-read-message -->
                    </div><!-- /.box-body -->
                    <div class="box-footer" style="margin-top: 1em;">
                      <div class="col-xs-12" style="margin-top: 0.5em; padding-left: 5px; padding-right: 0px;">
                        <span class="mailbox-read-time" style="margin-right: 1em;"><?php echo $newDate; ?></span>
                        <div class="pull-right mobile-left">
                          <?php
                          if(!$sentMessage){
                          ?>
                            <a class="btn btn-box-tool action subscribe primary"
                               href="<?php echo $this->getUrl(); ?>csmessaging/frontend/customercompose?id=<?php echo $chat->getSenderId() ?>&product_id=<?= $product_id ?>&subject=<?= urlencode($chat->getSubject()) ?>&vendor_id=<?= $chat->getVendorId() ?>">Reply</a>
                          <?php
                        }// end if not a sent message
                           ?>
                           <a style="float: right; margin-left: 0.7em;" target="_blank" class="btn btn-box-tool action subscribe primary" href="<?= $product->getProductUrl() ?>">View Listing</a>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </section>
</div>
<style>
.page-wrapper {
  min-height: 87%;
}
.right-sidebar-wrap{
  padding-left: 0px;
}
.columns::after {
  clear: none;
}
@media(max-width: 578px){
  .mailbox-read-time{
    font-size: 12px;
  }
  .mobile-left {
    float: left !important;
  }
  .page-main {
    padding-top: 0px !important;
  }
}
@media(min-width: 578px){
  .desktop-full {
    width: 100% !important;
  }
}
</style>

<script>
require([
    "jquery",
], ($) => {

  $(document).ready(function(){
    $('li:contains("Messages")').addClass('current');
  });
});
</script>
