<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMessaging
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

$collection = $this->getCollection();
$adminInboxCount = $this->_messagingHelper->getCustomerInboxCountForAdmin();
$vendorInboxCount = $this->_messagingHelper->getCustomerInboxCountForVendor();
?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="left-sidebar-wrap">
                <div class="box-header with-border box-folder">
                    <h3 class="box-title">Folders</h3>
                </div>

                <div class="box box-solid">

                    <div class="box-body no-padding">
                        <ul class="nav nav-pills nav-stacked">
                            <!-- <li>
                                <a href="<?php echo $this->getUrl('csmessaging/frontend/customercompose');//Mage::getUrl('csvendorchat/frontend/customercompose')?>"
                                   class="btn btn-block compose-tab">Compose</a>
                            </li> -->
                            <li>
                                <a class="fa fa-inbox" href="<?php echo $this->getUrl('csmessaging/frontend/inbox');//Mage::getUrl('csvendorchat/frontend/inbox')?>"><?php echo __(' Inbox'); ?>
                                    <span class="label label-primary pull-right"><?php if ($vendorInboxCount > 0) {
                                            echo '(';
                                            echo $vendorInboxCount;
                                            echo ')';
                                        } ?></span></a></li>
                            <li class="active"><a
                                        href="<?php echo $this->getUrl('csmessaging/frontend/sent');//Mage::getUrl('csvendorchat/frontend/sent')?>"
                                        class="sent-mail-tab fa fa-envelope-o"> Sent</a></li>

                        </ul>
                    </div><!-- /.box-body -->
                </div>
            </div><!-- /.col -->
            <div class="right-sidebar-wrap mail-send">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Sent</h3>
                        <?php echo $this->getPagerHtml(); ?>
                        <div class="clear"></div>
                    </div><!-- /.box-header -->
                    <div class="box-body no-padding">
                        <?php if (!$collection->count()): ?>
                            <p class="note-msg"><?php echo __('There are no sent items.') ?></p>
                        <?php else: ?>

                            <div class="table-responsive mailbox-messages">
                                <table class="table table-hover table-striped">
                                    <tbody>
                                    <?php if ($collection->getSize()): ?>
                                        <?php foreach ($collection as $msg => $value): ?>
                                            <tr>
                                                <td class="mailbox-name"><a
                                                            href="<?php echo $this->getUrl();//Mage::getBaseUrl()?>csmessaging/frontend/read?id=<?php echo $value['chat_id'] ?>"><?php echo $value['receiver_name'] ?></a>
                                                </td>
                                                <td class="mailbox-subject"><b><a href="<?php echo $this->getUrl();//Mage::getBaseUrl()?>csmessaging/frontend/read?id=<?php echo $value['chat_id'] ?>"><?php echo $value['subject'] ?></a></td>
                                                <td class="mailbox-subject"></b><a href="<?php echo $this->getUrl();//Mage::getBaseUrl()?>csmessaging/frontend/read?id=<?php echo $value['chat_id'] ?>"><?php echo substr($value['message'], 0, 16); ?></a>
                                                <?php
                                                  if(count($value['message']) > 16){
                                                    echo '...';
                                                  }
                                                 ?>
                                                </td>
                                                <td class="mailbox-attachment"></td>
                                                <td class="mailbox-date"><a href="<?php echo $this->getUrl();//Mage::getBaseUrl()?>csmessaging/frontend/read?id=<?php echo $value['chat_id'] ?>"><?php echo date("F d, Y g:i A", strtotime($value['time'])) ?></a></td>
                                                <td><span data-id="<?= $value['chat_id'] ?>" style="cursor: pointer;" class="fa fa-trash delete-message"></span></td>
                                            </tr>
                                        <?php endforeach ?>
                                    <?php endif; ?>
                                    </tbody>
                                </table><!-- /.table -->
                            </div><!-- /.mail-box-messages -->
                        <?php endif; ?>
                    </div><!-- /.box-body -->
                    <div class="box-footer no-padding">
                    </div>
                </div><!-- /. box -->
            </div><!-- /.col -->
            <div class="clear"></div>
        </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<div style="display: none" id="delete-message-modal">
  <form method="post" action="/csmessaging/frontend/savechat" id="delete-message-form">
    <div class="row" style="margin-bottom: 1em">
      <div class="col-md-12" style="margin-left: 1em;">
        <strong>Are you sure you want to delete this message?</strong>
      </div>
    </div>
  </form>
</div>
<style>
.right-sidebar-wrap{
  padding-left: 0px;
}
.delete-button {
  background-color: #db3b21;
  border-color: #db3b21;
  color: #ffffff;
  text-shadow: 1px 1px 0 rgba(0,0,0,0.25);
}
.limiter {
  display: none;
}
@media (max-width: 575.98px) {
  .modal-popup.modal-slide._inner-scroll .modal-inner-wrap {
      height: auto;
      width: 100% !important;
      min-height: 100%;
  }
  .modal-footer {
    padding-bottom: 0 !important;
    margin-top: 0 !important;
  }
  .modal-content {
    padding-bottom: 0 !important;
  }
}
</style>
<script>
require([
    "jquery",
    'Magento_Ui/js/modal/modal'
], ($, modal) => {
  $('.delete-message').click(function(){
      let chat_id = $(this).data('id');
      var deleteOptions = {
        type: 'popup',
        responsive: true,
        innerScroll: true,
        title: 'Delete Message',
        buttons: [{
          text: $.mage.__('Delete'),
          class: 'delete-button',
          click: function () {
            $.post('/api/messages/delete', { chat_id }, (response) => {
              window.location.reload();
            });
          }// end click function
        }]
      };
      var popup = modal(deleteOptions, $('#delete-message-modal'));
      $('#delete-message-modal').modal('openModal');
  });
  $(document).ready(function(){
    $('li:contains("Messages")').addClass('current');
  });
});
</script>
