<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */
$dataPostParam = '';
$logged_in = $block->isLoggedIn();
if ($logged_in) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}

// custom Login / Signup link
$label = $block->getLabel();
$label = str_replace('Sign In', 'Login / Signup', $label);

// custom home button
$label = str_replace('Sign Out', '<img style="margin-top: 0.25em" width="33em" src="/pub/media/icons/home-button.png" /></span>', $label);

// redirect to the account page
$dataPostParam = str_replace('\/logout', '', $dataPostParam);
$href = str_replace('/logout', '', $block->getLinkAttributes());
?>
<li class="authorization-link" data-label="<?php echo $this->helper(\Magento\Framework\EscapeHelper::class)->escapeHtmlAttr(__('or')); ?>">
    <a <?php /* @noEscape */ echo $href; ?><?php /* @noEscape */ echo $dataPostParam; ?>>
        <?php echo $label; ?>
    </a>
</li>
