
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();

$_order = $block->getOrder();
$order_number = $_order->getIncrementId();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');

$sql = "SELECT vendor_id FROM ced_csmarketplace_vendor_sales_order WHERE order_id =  '".$this->escapeQuote($order_number)."'";
$result = $connection->fetchAll($sql); // gives associated array, table fields as key in array.

if(count($result) > 0 && $result[0]['vendor_id'] == $customerSession->getVendorId()){
  $type = 'sold';
}else{
  $type = 'bought';
}// end if
?>
<tr id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">
    <td class="col name" data-th="<?php echo $block->escapeHtml(__('Item Name')); ?>">
        <strong class="product name product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></strong>

        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) :?>
            <?php echo $addtInfoBlock->setItem($_item)->toHtml(); ?>
        <?php endif; ?>
        <?php echo $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col seller" data-th="<?php echo $block->escapeHtml(__('Seller')); ?>">
      <dl class="item-options">
        <?php if ($_options = $block->getItemOptions()): ?>
         <?php foreach ($_options as $_option) : ?>
           <?php
                if($type == 'sold'){
                   echo $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp';
                 }else{
                   echo nl2br($block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])));
                 }
                 ?>
                 </dd>
         <?php endforeach; ?>
       <?php endif; ?>
         </dl>
    </td>
    <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
        <?php echo $block->getItemPriceHtml(); ?>
    </td>
    <td class="col qty" data-th="<?php echo $block->escapeHtml(__('')); ?>">
        </td>
    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
        <?php echo $block->getItemRowTotalHtml(); ?>
    </td>
</tr>
