<?php
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		$rating_opt = $this->getRatingOption();
		$order = $this->getOrder();
		$items = $order->getAllItems();
		$product = $items[0]->getProduct();
		$product_name = $product->getName();
		$vendor = $this->getVendor();
		$order_cust_id = $order->getCustomerId();
		$customer_id = $this->getSession()->getId();
		$customer = $objectManager->create('Magento\Customer\Model\Customer')->load($order_cust_id);

		if($customer_id !== $vendor->getCustomerId()){
			echo 'This is not your order.';
			return;
		}
		if($vendor->getName() == null){
			echo 'Could not find seller or order information.';
			return;
		}
		if($product_name == null){
			echo 'Could not find item information.';
			return;
		}
    if (!$order->canShip()) {
?>
	<div class="message info">
		<div>
			You have already entered a tracking number for this order.
		</div>
	</div>
<?php
      return;
		}// end if cant ship the order
?>
<div class="block review-add">
    <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('Enter Tracking') ?></strong></div>
<div class="block-content">
	<?php if ($this->getSession() != null && $this->getSession()->isLoggedIn()){ ?>
<form action="/api/tracking" class="tracking-form" method="post" id="tracking-form" data-role="order-tracking-form" data-bind="scope: 'review-form'">
		<input type="hidden" name="order_id" value="<?= $order->getId() ?>" />
    <fieldset class="fieldset review-fieldset" data-hasrequired="<?php __('* Required Fields'); ?>">
        <legend class="legend review-legend"><span><?php /* @escapeNotVerified */ echo __("Send Tracking To: &nbsp;&nbsp;<span style='font-weight: bold'>".$customer->getName()."</span>"); ?></span></legend><br />
				<legend class="legend review-legend"><span><?php /* @escapeNotVerified */ echo __("Item Name: &nbsp;&nbsp;<span style='font-weight: bold'>".$product->getName()."</span>"); ?></span></legend><br />
        <div class="field review-field-text required">
            <label style="text-align: left;" for="review_field" class="label"><span><?php /* @escapeNotVerified */ echo __('Tracking Number:') ?></span></label>
            <div class="control">
                <input pattern="([A-z0-9À-ž\s]){5,}" type="text" name="tracking_number" id="tracking_number" style="width: 45%" required minlength="5" data-bind="value: review().detail" />
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar review-form-actions">
        <div class="primary actions-primary">
            <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Submit') ?></span></button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
{
    "[data-role=product-review-form]": {
        "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
    },
    "#review-form": {
        "Magento_Review/js/error-placement": {}
    }
}
</script>
  <?php } else { ?>
	<div class="message info notlogged" id="review-form">
        <div>
<?php
  $url = 'https://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
  $encoded_url = base64_encode($url);
?>
            <?php  echo __('Only registered users can write reviews. Please, <a href="/customer/account/login/referer/'.$encoded_url.'">Sign in</a> or <a href="/customer/account/create?referer='.urlencode($url).'">create an account</a>', $this->getLoginLink(),$this->getLoginLink()) ?>
        </div>
    </div>
  <?php } ?>
</div>
</div>
<style>
@media(min-width: 576px){
	.abs-margin-for-forms-desktop, .fieldset .legend, .column:not(.sidebar-main) form .actions-toolbar, .column:not(.sidebar-additional) form .actions-toolbar, .login-container .fieldset::after {
		margin-left: 41.2%;
	}
	.label {
		width: 15% !important;
	}
}
</style>
