<?php
/**
* Sell Form
*/
$new_attr_id = 227;
$all_category_id = 105;
if(isset($_GET['id']) && $_GET['id'] != null)
{
    $product_id = $_GET['id'];
    $mode = "Edit";
    $title = "Edit Listing";

    // retreive the seller's product
    $model = \Magento\Framework\App\ObjectManager::getInstance();
    $product = $model->create('Magento\Catalog\Model\Product')->load($product_id);
    $productSku = $product->getSku();
    $vendorProduct = $model->create('Ced\CsMarketplace\Model\Vproducts')->getCollection()->addFieldToFilter('sku', $productSku)->addFieldToFilter('check_status',['nin'=>3])->getFirstItem();

    // validation, make sure this product was created by the signed in user
    if($vendorProduct->getVendorId() !== $block->getVendorId()){
      echo "You do not have access to view this page.";
      exit;
    }// end if this isn't the seller's product

    // list of category ids for product
    $category_ids = array_values(array_diff($product->getCategoryIds(), [$all_category_id]));
    $lowestcategory = $model->create('Magento\Catalog\Model\Category')->load($category_ids[0]);
}else
{
  $product_id = null;
  $mode = "Create";
  $title = "Sell";
}// end if we have a preset product id

?>
<title>Sell</title>
<h1><?= $title ?></h1><br/>
<div id="error" class="alert" style="display: none">
 <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
 <strong><span id="error-text"></span></strong>
</div>
<form class="form" action="/api/product" method="post" id="sell_form" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <input type="hidden" name="latitude" id="latitude" value="" />
    <input type="hidden" name="longitude" id="longitude" value="" />
<?php
  if($mode === "Edit"){
?>
  <input type="hidden" name="product_id" value="<?= $product_id ?>" />
<?php
}// end if mode === "edit"
 ?>
    <fieldset class="fieldset" id="app">
        <div class="field name">
            <label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Item Name') ?></span></label>
            <div class="control">
                <input class="form-input" name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Item Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name')) ?>" class="input-text" type="text" data-validate="{required:true, maxlength: 24}" v-model="form_data.name" />
            </div>
        </div>
        <div class="field title_description">
            <label class="label" for="title_description"><span><?php /* @escapeNotVerified */ echo __('Title Description') ?></span></label>
            <div class="control">
                <input class="form-input" name="title_description" id="title_description" title="<?php /* @escapeNotVerified */ echo __('Title Description') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('title_description')) ?>" class="input-text" type="text" data-validate="{required:true, maxlength: 42}" v-model="form_data.title_description" />
            </div>
        </div>
        <div class="field price">
          <label class="label" for="price"><span><?php /* @escapeNotVerified */ echo __('Price') ?></span></label>
          <div class="col-md-1" style="padding-left: 0">
            <div class="control">
              <input style="width: 7em !important;" class="form-input" name="price" id="price" title="<?php /* @escapeNotVerified */ echo __('Price') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('price')) ?>" class="input-text" type="number" data-validate="{required:true, number: true, min: 20}" v-model="form_data.price" />
            </div>
          </div>
          <div class="col-md-3 service-fee">
            <div class="control">
              <strong class="label" style="padding-right: 15px"><span><?php /* @escapeNotVerified */ echo __('Service Fee') ?></span></strong>
              <input disabled style="width: 40% !important; color: black;" class="form-input" name="price" id="service_fee" title="<?php /* @escapeNotVerified */ echo __('Service Fee') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('service_fee')) ?>" class="input-text" type="number" data-validate="{required:true, number: true, min: 20}" v-model="serviceFee" />
            </div>
          </div>
          <div class="col-md-3">
            <strong style="padding-right: 15px;"><span><?php /* @escapeNotVerified */ echo __('Your Profit') ?></span></strong>
            <input disabled style="width: 40% !important; color: black;" class="form-input" name="price" id="price" title="<?php /* @escapeNotVerified */ echo __('Price') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('price')) ?>" class="input-text" type="number" data-validate="{required:true, number: true, min: 20}" v-model="yourProfit" />
          </div>
        </div>
        <div class="field category">
            <label class="label" for="category_select"><span><?php /* @escapeNotVerified */ echo __('1st Category') ?></span></label>
            <div class="control">
                <select class="form-input" style="cursor: pointer;" name="category" id="category_select" data-validate="{required:true}" v-model="form_data.category">
                  <option value=""></option>
                  <option v-for="(data, category) in categories" v-bind:value="category">
                  {{ category }}
                  </option>
                </select>
            </div>
        </div>
        <div class="field subcategory">
            <label class="label" for="subcategory_select"><span><?php /* @escapeNotVerified */ echo __('2nd Category') ?></span></label>
            <div class="control">
                <select class="form-input" style="cursor: pointer" name="subcategory" id="subcategory_select" data-validate="{required:true}" v-model="form_data.subcategory">
                  <option value=""></option>
                  <option v-for="(data, subcategory) in subcategories" v-bind:value="subcategory">
                  {{ subcategory }}
                  </option>
                </select>
            </div>
        </div>
        <div class="field lowestcategory">
            <label class="label" for="lowestcategory_select"><span><?php /* @escapeNotVerified */ echo __('3rd Category') ?></span></label>
            <div class="control">
                <select class="form-input" style="cursor: pointer" name="lowestcategory" id="lowestcategory_select" data-validate="{required:true}" v-model="form_data.lowestcategory">
                  <option value=""></option>
                  <option v-for="lowestcategory in lowestcategories" v-bind:value="lowestcategory.id">
                  {{ lowestcategory.name }}
                  </option>
                </select>
            </div>
        </div>
        <div class="field condition">
            <label class="label" for="condition"><span><?php /* @escapeNotVerified */ echo __('Condition') ?></span></label>
            <div class="control">
                <select class="form-input" style="cursor: pointer" name="condition" id="conditon" data-validate="{required:true}" v-model="form_data.condition">
                  <option value=""></option>
                  <option value="<?= $new_attr_id ?>">New</option>
                  <option value="<?= $new_attr_id + 1 ?>">Like New</option>
                  <option value="<?= $new_attr_id + 2 ?>">Good</option>
                  <option value="<?= $new_attr_id + 3 ?>">Used</option>
                </select>
            </div>
        </div>
        <div class="field local">
            <label class="label" for="local"><span><?php /* @escapeNotVerified */ echo __('Local / Global') ?></span></label>
            <div class="control">
                <div class="ck-button">
                  <label style="cursor: pointer;">
                    <input class="local_global" style="margin-left: 0.2em; margin-top: 0.3em;" type="checkbox" value="231" name="local_global[]" id="local" data-validate="{'validate-local-global': true}" v-model="form_data.local_global" /> <span style="margin-right: 1.5em; width: 100%">&nbsp;<strong>Local</strong></span>
                  </label>
                </div>
                <div class="ck-button">
                  <label style="cursor: pointer;">
                      <input class="local_global" style="margin-left: 0.2em; margin-top: 0.3em;" type="checkbox" value="232" name="local_global[]" id="global" v-model="form_data.local_global" /> <span style="margin-right: 1.5em; width: 100%; height: 100%;"> &nbsp;&nbsp;<strong>Global</strong></span>
                  </label>
                </div>
                <div style="color: #e02b27; font-size: 1.2rem;" class="custom-error" id="local_global_error" v-if="local_global_error" v-cloak>Please select at least one option.</div>
            </div>
        </div>
        <span id="mobile1" style="display: none;"><br/></span>
        <div class="field images">
            <label class="label" for="images"><span><?php /* @escapeNotVerified */ echo __('Images') ?></span></label>
            <div class="control">
              <!-- Fine Uploader DOM Element ====================================================================== -->
              <div class="form-input" id="fine-uploader"></div>
            </div>
        </div>
        <div class="field description">
            <label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('Details') ?></span></label>
            <div class="control">
                <textarea class="form-input" name="description" id="description" title="<?php /* @escapeNotVerified */ echo __('Description') ?>" class="input-text" cols="5" rows="5" data-validate="{required:true}" v-model="form_data.description"><?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('description')) ?></textarea>
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" id="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary" disabled>
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>
<style>
.page-title-wrapper {
  display: none;
}
.qq-gallery .qq-thumbnail-wrapper {
  height: 105px;
}
.qq-gallery .qq-upload-list li {
  height: 11em;
}
/* The alert message box */
.alert {
   padding: 20px;
   background-color: #f2dede; /* Red */
   color: #a94442;
   margin-bottom: 15px;
}

.ck-button {
    margin:4px;
    background-color:#EFEFEF;
    border-radius: 4px;
    border:1px solid #D0D0D0;
    overflow:auto;
    float:left;
    padding: 6px;
}

.ck-button:hover {
    background: #3CBBD8;
}

.ck-button label {
    float:left;
    width: 6.0em;
}

.ck-button label span {
    text-align:center;
    padding: 3px 0px 3px;
    display: block;
}

.ck-button label input {
    position:absolute;
}

.ck-button input:checked + span {
    color:#fff;
}

/* The close button */
.closebtn {
   margin-left: 15px;
   color: #565252;
   font-weight: bold;
   float: right;
   font-size: 22px;
   line-height: 20px;
   cursor: pointer;
   transition: 0.3s;
}

/* When moving the mouse over the close button */
.closebtn:hover {
   color: black;
}
.qq-gallery .qq-upload-button {
  background-color: #3ec2df;
  font-weight: 650;
}

.blue-background {
  background: #3CBBD8;
}

@media (max-width: 575.98px) {
  #mobile1 {
    display: block !important;
    margin-top: 3em;
  }
}

@media (min-width: 576px) {
  .form-input {
    width: 70% !important;
  }
  .service-fee {
    text-align: center;
    padding-left: 2em;
  }
}
</style>
<script>
require([
    "jquery",
    "mage/mage",
    "mage/validation",
    "vue",
    "fine-uploader"
], ($, mage, validation, Vue, qq) => {
    // initialize a new Vue app
    var app = new Vue({
      el: '#app',
      data: {
        categories: [],
        subcategories: [],
        lowestcategories: [],
        image_paths: [],
        local_global_error: false,
        image_error: false,
        form_data: {local_global: []}
      },
      computed: {
        serviceFee: function () {
          return this.form_data.price * 0.1;
        },
        yourProfit: function(){
          return this.form_data.price - (this.form_data.price * 0.1);
        }
      }
    });

<?php
  if($mode === "Edit"){
?>
  app.form_data.name = "<?= $product->getName() ?>";
  app.form_data.title_description = "<?= $product->getData('title_description'); ?>";
  app.form_data.price = "<?= $product->getPrice() ?>";
  app.form_data.category = "<?= $lowestcategory->getParentCategory()->getParentCategory()->getName() ?>";
  app.form_data.subcategory = "<?= $lowestcategory->getParentCategory()->getName() ?>";
  app.form_data.lowestcategory = "<?= $category_ids[0] ?>";
  app.form_data.condition = "<?= $product->getData('condition') ?>";
  app.form_data.description = "<?= $product->getDescription() ?>";
  let local_global = "<?= $product->getData('local_global') ?>";

  if(local_global.includes("231")){
    // local
    app.form_data.local_global.push(231);
  }
  if(local_global.includes("232")){
    // global
    app.form_data.local_global.push(232);
  }
<?php
}// end if mode == 'edit'
?>
    // sell form submission function, ensure form is valid
    $('#sell_form').submit(function(){
      if($(this).valid()){

        if(app.image_paths.length == 0){
          alert("You must upload at least one image.");
          return false;
        }// end if no images selected

        // remove file inputs (causes bug on iphone)
        $('input[type="file"]').remove();

        // append the image paths to the form
        $('<input>').attr({
          type: 'hidden',
          name: 'image_paths',
          value: app.image_paths.join()
        }).appendTo('#sell_form');

        // submit the sell form via ajax
        $.ajax({
          data: new FormData($(this)[0]),
          processData: false,
          contentType: false,
          url: $(this).attr('action'),
          type: $(this).attr('method'),
          showLoader: true,
          cache: true,
          success: function(data){
            if(data.error != undefined){
              $('#error-text').html(data.error);
              $('#error').show();
            }else if(data.success == 'Y'){
              window.location = '/customer/account/listings';
            }
          }
        });
        return false;
      }
    });

    // initialize a fine uploader client
    let first_image = false;
    var uploader = new qq.FineUploader({
        element: document.getElementById('fine-uploader'),
        template: 'qq-template',
        session: {
          endpoint: "/api/Image/Get",
          params: {
            product_id: "<?= isset($_GET['id']) ? $_GET['id'] : '' ?>"
          }
        },
        request: {
            endpoint: "/api/Image/Upload"
        },
        chunking: {
            enabled: true
        },
        resume: {
            enabled: true
        },
        deleteFile: {
            enabled: true,
            method: "POST",
            endpoint: "/api/Image/Delete",
            forceConfirm: true,
            params: {
              product_id: '<?= isset($_GET['id']) ? $_GET['id'] : '' ?>'
            }
        },
        validation: {
            allowedExtensions: ['jpeg', 'jpg', 'png'],
            itemLimit: 10,
            sizeLimit: 5120000  // 5 MB
        },
        scaling: {
          sendOriginal: false,
          includeExif: true,
          sizes: [{ maxSize: 1400 }]
        },
        thumbnails: {
            placeholders: {
                notAvailablePath: "/pub/media/icons/not_available-generic.png",
                waitingPath: "/pub/media/icons/waiting-generic.png"
            }
        },
        callbacks: {
            onComplete: function(id, name, response) {
                var previewLink = qq(this.getItemByFileId(id)).getByClass('preview-link')[0];
                if (response.success) {
                    previewLink.setAttribute("href", `/pub/media${response.path}`);
                    app.image_paths.push(response.path);
                }// end if success
                $('.qq-upload-size').hide();
                $('.qq-upload-file').hide();
                if(!first_image){
<?php
  if(!isset($_GET['id']) || $_GET['id'] == null){
 ?>
                  $('.qq-upload-delete').first().click((e) => {
                    alert("You cannot remove the first image. <?= !isset($_GET['id']) || $_GET['id'] == null ? "Please refresh the page to do so." : '' ?>");
                    return false;
                  });
<?php
}// end if creating a new product
?>
                  first_image = true;
                }// end if not first image
            },
            onDeleteComplete: function(id, xhr) {
              let response = JSON.parse(xhr.response);
              if(response.success){
                // remove the path from our client side list of image paths
                let index = app.image_paths.indexOf(response.path);
                if (index > -1) {
                  app.image_paths.splice(index, 1);
                }// end if valid index
              }else if(response.error){
                alert(response.error);
              }// end if success
            },
            onSessionRequestComplete: function(data) {
              // successfully retreived images from server
              app.image_paths = data.map(image => image.uuid);
              $('.qq-upload-size').hide();
              $('.qq-upload-file').hide();
              $('.qq-upload-delete').first().click((e) => {
                alert("You cannot remove the first image. <?= !isset($_GET['id']) || $_GET['id'] == null ? "Please refresh the page to do so." : '' ?>");
                return false;
              });
            }
        }
    });

    // add custom validation to our form
    addCustomValidation();

    // initial api requests
    $.get('/api/categories', (data) => {
      app.categories = data;

      if(app.form_data.category != null){
        app.subcategories = app.categories[app.form_data.category];

        if(app.form_data.subcategory != null){
          app.lowestcategories = app.subcategories[app.form_data.subcategory];
          $('.subcategory').show();
          if(app.form_data.lowestcategory != null){
              $('.lowestcategory').show();
          }// end if lowest category set
        }// end if subcategory set
      }// end if category set
    });

    // initialize validation
    $('#sell_form').mage('validation', {});

    // category change function
    $('#category_select').change(function() {
      let category = this.value;
      if(category == ''){
        app.subcategories = [];
        $('.subcategory').hide();
        $('.lowestcategory').hide();
      }else{
        app.subcategories = app.categories[category];
        $('#subcategory_select').val('');
        $('#lowestcategory_select').val('');
        $('.lowestcategory').hide();
        $('.subcategory').show();
      }
    });

    // subcategory change function
    $('#subcategory_select').change(function(){
      let subcategory = this.value;
      if(subcategory == ''){
        app.lowestcategories = [];
        $('.lowestcategory').hide();
      }else{
        app.lowestcategories = app.subcategories[subcategory];
        if(isNaN(app.lowestcategories)){
          $('#lowestcategory_select').val('');
          $('.lowestcategory').show();
        }
      }
    });

   // after everything loads, add our click handler
   $('#submit').prop('disabled', false);

   // click function for local checkbox
   $('#local').click(getLocation);

   $('.local_global').click(function(){
     let checkbutton = $(this).closest('.ck-button');
     if(this.checked){
       checkbutton.addClass('blue-background');
     }else{
       checkbutton.removeClass('blue-background');
     }
   });

   var pos;
   /**************************************************
   ******************* FUNCTIONS *********************
   **************************************************/
   function getLocation() {
     // Try HTML5 geolocation
     if(!document.getElementById("local").checked || pos) return;
     if (navigator.geolocation) {
       $('#submit').prop('disabled', true);
       navigator.geolocation.getCurrentPosition(function(position) {
         pos = {
           lat: position.coords.latitude,
           lng: position.coords.longitude
         };
         $('#latitude').val(`${pos.lat}`);
         $('#longitude').val(`${pos.lng}`);
         $('#submit').prop('disabled', false);
       }, function() {
         document.getElementById("local").checked = false;
         alert('You must give Resold access to your location to post locally. Please allow location permissions by clicking the lock in the top left corner of the browser.');
         $('#submit').prop('disabled', false);
         handleLocationError(true, infoWindow, map.getCenter());
       });
     } else {
       // Browser doesn't support Geolocation
       handleLocationError(false, infoWindow, map.getCenter());
     }
   };
   function addCustomValidation() {
     $.validator.addMethod(
        'validate-local-global',
        function (value) {
            // custom validation
            if(!document.getElementById('local').checked && !document.getElementById('global').checked){
              app.local_global_error = true;
              return false;
            }
            app.local_global_error = false;
            return true;
          }
      );
  };
  function handleLocationError(browserHasGeolocation, infoWindow, pos) {
    infoWindow.setPosition(pos);
    infoWindow.setContent(browserHasGeolocation ? 'Error: The Geolocation service failed.' : 'Error: Your browser doesn\'t support geolocation.');
    infoWindow.open(map);
  };
});

<?php
if(isset($_GET['code']) && $_GET['code'] != null){
?>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.agent='dvapptrian';n.queue=[];
t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');

fbq('init', '165147020823726');
fbq('trackCustom', 'SellerRegistration', {});
<?php
}// end if user just signed up with stripe
?>
</script>
<!-- Fine Uploader Customized Gallery template
 ====================================================================== -->
<script type="text/template" id="qq-template">
   <div class="qq-uploader-selector qq-uploader qq-gallery" qq-drop-area-text="Drop files here">
       <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
           <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
       </div>
       <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
           <span class="qq-upload-drop-area-text-selector"></span>
       </div>
       <div class="qq-upload-button-selector qq-upload-button">
           <div>Upload Image</div>
       </div>
       <span class="qq-drop-processing-selector qq-drop-processing">
           <span>Processing dropped files...</span>
           <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
       </span>
       <ul class="qq-upload-list-selector qq-upload-list" role="region" aria-live="polite" aria-relevant="additions removals">
           <li>
               <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
               <div class="qq-progress-bar-container-selector qq-progress-bar-container">
                   <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
               </div>
               <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
               <div class="qq-thumbnail-wrapper">
                   <a class="preview-link" target="_blank">
                       <img class="qq-thumbnail-selector" qq-max-size="120" qq-server-scale>
                   </a>
               </div>
               <button type="button" class="qq-upload-cancel-selector qq-upload-cancel">X</button>
               <button type="button" class="qq-upload-retry-selector qq-upload-retry">
                   <span class="qq-btn qq-retry-icon" aria-label="Retry"></span>
                   Retry
               </button>
               <div class="qq-file-info">
                   <div class="qq-file-name">
                       <span class="qq-upload-file-selector qq-upload-file"></span>
                       <span class="qq-edit-filename-icon-selector qq-edit-filename-icon" aria-label="Edit filename"></span>
                   </div>
                   <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                   <span class="qq-upload-size-selector qq-upload-size"></span>
                   <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">
                       <span class="qq-btn qq-delete-icon" aria-label="Delete"></span>
                   </button>
                   <button type="button" class="qq-btn qq-upload-pause-selector qq-upload-pause">
                       <span class="qq-btn qq-pause-icon" aria-label="Pause"></span>
                   </button>
                   <button type="button" class="qq-btn qq-upload-continue-selector qq-upload-continue">
                       <span class="qq-btn qq-continue-icon" aria-label="Continue"></span>
                   </button>
               </div>
           </li>
       </ul>
       <dialog class="qq-alert-dialog-selector">
           <div class="qq-dialog-message-selector"></div>
           <div class="qq-dialog-buttons">
               <button type="button" class="qq-cancel-button-selector">Close</button>
           </div>
       </dialog>
       <dialog class="qq-confirm-dialog-selector">
           <div class="qq-dialog-message-selector"></div>
           <div class="qq-dialog-buttons">
               <button type="button" class="qq-cancel-button-selector">No</button>
               <button type="button" class="qq-ok-button-selector">Yes</button>
           </div>
       </dialog>
       <dialog class="qq-prompt-dialog-selector">
           <div class="qq-dialog-message-selector"></div>
           <input type="text">
           <div class="qq-dialog-buttons">
               <button type="button" class="qq-cancel-button-selector">Cancel</button>
               <button type="button" class="qq-ok-button-selector">Ok</button>
           </div>
       </dialog>
   </div>
</script>
