<?php

/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category  Ced
  * @package   Ced_CsVendorReview
  * @author    CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license      http://cedcommerce.com/license-agreement.txt
  */

?>

<?php
	$vendor = $this->getVendor();
	$detail_rating=$this->getRatingDetails();
	if($this->isActivated()){

	$width = $this->getVendorRating();
	$url="";
	$url = $this->getUrl('csvendorreview/rating/lists', array('id'=>$this->getVendorId()));
?>
<?php
if(strpos($_SERVER['REQUEST_URI'], '/review/customer') === FALSE){
?>
<h1>Reviews for <?= $vendor->getName() ?><a href="<?= $vendor->getVendorShopUrl() ?>"><button style="margin-left: 2em;" class="btn btn-primary">View Store</button></a></h1>
<?php
}else{
?>
<hr style="margin-top: -0.8em;" />
<?php
}
?>
<div class="block">
    <div class="block-content" style="padding-top: 10px; padding-bottom: 20px;	">
				<?php if($width > 1){ ?>
						<div class="col-md-1" style="margin-top: 0.3em;">
            	<strong><span><??><?php echo __('Average	') ?></span></strong>
						</div>
					<div class="col-md-2">
						<div class="rating-summary">
							 <div title="<?php echo $width ?>%" class="rating-result">
								 <span style="width:<?php echo $width ?>%;"><span><?php echo $width ?>%</span></span>
							 </div>
						</div>
					</div>
				<?php foreach($detail_rating as $key=>$dr){?>
						<div class="col-md-1" style="margin-top: 0.3em">
            	<strong><span><?php echo $key ?></span></strong>
						</div>
						<div class="col-md-2">
							<div class="rating-summary">
								 <div title="<?php echo ceil($dr['rating']/$dr['count']) ?>%" class="rating-result">
									 <span style="width:<?php echo ceil($dr['rating']/$dr['count']) ?>%;"><span><?php echo ceil($dr['rating']/$dr['count']) ?>%</span></span>
								 </div>
							</div>
						</div>
				<?php } ?>

				<?php } else {?>
                <?php } ?>
    </div>
</div>
<?php } ?><hr style="margin-bottom: 0; margin-top: -0.3em;" id="horizontal-rule" />

<style>
.review-item {
	padding-top: 0;
}
.block, .block-banners, .block-banners-inline {
	margin-bottom: 1em !important;
}
</style>
