<?php /** @var $block \Potato\Compressor\Block\RequireJsDataCollector */ ?>
<script type="text/javascript" <?php echo $block->getScriptDataKey();?>="<?php echo $block->getRouteKey();?>" data-po-cmp-ignore-merge="">
    require(['Potato_Compressor/js/require-js-data-collector'], function (dataCollector) {
        dataCollector.init(
            <?php echo \Zend_Json::encode($block->getRouteKey());?>,
            <?php echo \Zend_Json::encode($block->getRequestUrl());?>
        );
        dataCollector.run();
    });
</script>