<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php

$model =  \Magento\Framework\App\ObjectManager::getInstance();
$productSku = $_product->getSku();
$VendorProduct = $model->create('Ced\CsMarketplace\Model\Vproducts')->getCollection()->addFieldToFilter('sku',$productSku)->addFieldToFilter('check_status',['nin'=>3])->getFirstItem();
$sessionId = $model->create('Magento\Customer\Model\Session')->getVendorId();
$VendorId = $VendorProduct->getVendorId();

// whether this is the current seller's product
$userProduct = $sessionId == $VendorId;
if($userProduct){
  $buttonTitle = __('Edit');
  $buttonHtml = '<a href="/sell"
                    title="'.$buttonTitle.'"
                    class="action primary tocart"
                    id="product-addtocart-button">
                    <span>'.$buttonTitle.'</span>
                </a>';
}else{
  $buttonTitle = __('Purchase');
  $buttonHtml = '<button type="submit"
                    title="'.$buttonTitle.'"
                    class="action primary tocart"
                    id="product-addtocart-button">
                    <span>'.$buttonTitle.'</span>
                </button>';
}
?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <?php echo $buttonHtml ?>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<?php endif; ?>
