<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php

$model =  \Magento\Framework\App\ObjectManager::getInstance();
$productSku = $_product->getSku();
$VendorProduct = $model->create('Ced\CsMarketplace\Model\Vproducts')->getCollection()->addFieldToFilter('sku',$productSku)->addFieldToFilter('check_status',['nin'=>3])->getFirstItem();
$customer = $model->create('Magento\Customer\Model\Session');
$sessionId = $customer->getVendorId();
$VendorId = $VendorProduct->getVendorId();

// whether this is the current seller's product
$userProduct = $sessionId == $VendorId;
if($userProduct){
  $buttonTitle = __('Edit');
  $buttonHtml = '<button type="submit"
                    title="'.$buttonTitle.'"
                    class="action primary tocart product-edit"
                    style="float: left; margin-bottom: 0.3em; width: 75%; cursor: pointer;"
                    id="product-addtocart">
                    <span>'.$buttonTitle.'</span>
                </button>';
}else{
  $buttonTitle = __('Purchase');
  $buttonHtml = '<button type="submit"
                    title="'.$buttonTitle.'"
                    class="action primary tocart"
                    style="float: left; margin-bottom: 0.3em; width: 75%; cursor: pointer;"
                    id="product-addtocart">
                    <span>'.$buttonTitle.'</span>
                </button>';
}
?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <?php echo $buttonHtml ?>
<?php if (!$userProduct): ?>
              <a href="#"
                    title=""
                    class="action primary custom-button"
                    style="float: left; margin-bottom: 0.3em; width: 75%; cursor: pointer;"
                    id="product-offer-button">
                    <span>Send Offer</span>
              </a>
              <a href="#"
                    title=""
                    class="action primary custom-button contact-seller"
                    style="float: left; width: 75%; cursor: pointer;"
                    id="product-message-button">
                    <span>Contact Seller</span>
              </a>
<?php endif; ?>
<?php if ($userProduct): ?>
              <a href="#"
                    title=""
                    class="action primary custom-button"
                    style="float: left; margin-bottom: 0.3em; width: 75%; cursor: pointer;"
                    id="product-delete-button">
                    <span>Delete</span>
              </a>
<?php endif; ?>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<div style="display: none" id="contact-seller-modal">
  <form method="post" action="/csmessaging/frontend/savechat" id="contact-seller-form">
    <input type="hidden" name="email_subject" id="email_subject" value="<?= $_product->getName() ?>" />
    <input type="hidden" name="vendor_id" id="vendor_id" value="<?= $VendorId ?>" />
    <input type="hidden" name="sent_to_vendor" value="Y" />
    <div class="row" style="margin-bottom: 1em">
      <div class="col-md-2">
        <strong>Item:</strong>
      </div>
      <div class="col-md-6">
        <span class="item-name"></span>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2">
        <strong>Message:</strong>
      </div>
      <div class="col-md-8">
        <textarea id="text_email_contact_seller" name="text_email" rows="10"></textarea>
      </div>
    </div>
  </form>
</div>
<div style="display: none" id="make-offer-modal">
  <form method="post" action="/csmessaging/frontend/savechat" id="contact-seller-form">
    <input type="hidden" name="email_subject" id="email_subject" value="<?= $_product->getName() ?>" />
    <input type="hidden" name="vendor_id" id="vendor_id" value="<?= $VendorId ?>" />
    <input type="hidden" name="sent_to_vendor" value="Y" />
    <div class="row" style="margin-bottom: 1em">
      <div class="col-md-2">
        <strong>Item:</strong>
      </div>
      <div class="col-md-6">
        <span class="item-name"></span>
      </div>
    </div>
    <div class="row" style="margin-bottom: 1em">
      <div class="col-md-2">
        <strong>Offer ($):</strong>
      </div>
      <div class="col-md-2">
        <input type="number" name="offer_price" id="offer_price" />
      </div>
    </div>
    <div class="row">
      <div class="col-md-2">
        <strong>Message:</strong>
      </div>
      <div class="col-md-8">
        <textarea id="text_email_offer" name="text_email" rows="10"></textarea>
      </div>
    </div>
  </form>
</div>

<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<?php endif; ?>
<style>
.product-info-main .box-tocart .action.tocart, .product-options-bottom .box-tocart .action.tocart, .bundle-options-container .box-tocart .action.tocart, .product-info-main .box-tocart .action.instant-purchase, .product-options-bottom .box-tocart .action.instant-purchase, .bundle-options-container .box-tocart .action.instant-purchase {
  min-width: 179px;
}
.custom-button {
  line-height: 2.2rem !important;
  padding: 15px 17px !important;
  font-size: 1.8rem !important;
  min-width: 179px;
}
.product-info-main .product-info-stock-sku {
  padding-bottom: 0px;
}
@media (max-width: 575.98px) {
  .tocart, .custom-button {
    width: 100% !important;
  }
  .contact-seller {
    margin-bottom: 1em;
  }
}
.modal-inner-wrap {
  width: 40% !important;
}
.send-button {
  float: right;
}
@media (max-width: 575.98px) {
  .modal-popup.modal-slide._inner-scroll .modal-inner-wrap {
      height: auto;
      width: 100% !important;
      min-height: 100%;
  }
}
</style>
<script>
require(['jquery', 'Magento_Ui/js/modal/modal'], ($, modal) => {

$(document).ready(() => {

    $('.product-edit').click((e) => {
      e.preventDefault();
      window.location = '/sell';
    });

    var options = {
      type: 'popup',
      responsive: true,
      innerScroll: true,
      title: 'Contact Seller - ' + $('.listedBy:first').text().replace('Listed by: ', ''),
      buttons: [{
        text: $.mage.__('Send'),
        class: 'send-button',
        click: function () {
          var data = {
            'vendor_id': $('#vendor_id').val(),
            'email_subject': $('#email_subject').val(),
            'text_email': $('#text_email_contact_seller').val()
          };
          $.post('/csmessaging/frontend/savechat', data, (response) => {
            $('#text_email_contact_seller').val('');
            this.closeModal();
          });
        }
      }]
    };
    $('#product-message-button').click(() => {
<?php
  if($customer->isLoggedIn()){
?>
    options.title = options.title.replace('Send Offer', 'Contact Seller');
    $('.item-name').html($('.page-title:first').text());
    var popup = modal(options, $('#contact-seller-modal'));
    $('#contact-seller-modal').modal('openModal');
<?php
  }else{
?>
    $('.authorization-link a:first')[0].click();
    console.log('should we get here message');
<?php
  }// end if customer is logged in
?>
  });
  $('#product-offer-button').click(() => {
<?php
  if($customer->isLoggedIn()){
?>
    options.title = options.title.replace('Contact Seller', 'Send Offer');
    $('.item-name').html($('.page-title:first').text());
    var popup = modal(options, $('#make-offer-modal'));
    $('#make-offer-modal').modal('openModal');
<?php
  }else{
?>
    console.log('should we get here offer');
    $('.authorization-link a:first')[0].click();
<?php
  }// end if customer is logged in
?>
    });
  });
});
</script>
