<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php

$model =  \Magento\Framework\App\ObjectManager::getInstance();
$productSku = $_product->getSku();
$VendorProduct = $model->create('Ced\CsMarketplace\Model\Vproducts')->getCollection()->addFieldToFilter('sku',$productSku)->addFieldToFilter('check_status',['nin'=>3])->getFirstItem();
$sessionId = $model->create('Magento\Customer\Model\Session')->getVendorId();
$VendorId = $VendorProduct->getVendorId();

// whether this is the current seller's product
$userProduct = $sessionId == $VendorId;
if($userProduct){
  $buttonTitle = __('Edit');
  $buttonHtml = '<a href="/sell"
                    title="'.$buttonTitle.'"
                    class="action primary tocart"
                    style="width: 75%"
                    id="product-addtocart-button">
                    <span>'.$buttonTitle.'</span>
                </a><br/>';
}else{
  $buttonTitle = __('Purchase');
  $buttonHtml = '<button type="submit"
                    title="'.$buttonTitle.'"
                    class="action primary tocart"
                    style="float: left; margin-bottom: 0.3em; width: 75%"
                    id="product-addtocart-button">
                    <span>'.$buttonTitle.'</span>
                </button>';
}
?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <?php echo $buttonHtml ?>
<?php if (!$userProduct): ?>
              <a href="#"
                    title=""
                    class="action primary custom-button"
                    style="float: left; margin-bottom: 0.3em; width: 75%"
                    id="product-offer-button">
                    <span>Send Offer</span>
              </a>
              <a href="#"
                    title=""
                    class="action primary custom-button contact-seller"
                    style="float: left; width: 75%"
                    id="product-message-button">
                    <span>Contact Seller</span>
              </a>
<?php endif; ?>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<?php endif; ?>
<style>
.product-info-main .box-tocart .action.tocart, .product-options-bottom .box-tocart .action.tocart, .bundle-options-container .box-tocart .action.tocart, .product-info-main .box-tocart .action.instant-purchase, .product-options-bottom .box-tocart .action.instant-purchase, .bundle-options-container .box-tocart .action.instant-purchase {
  min-width: 179px;
}
.custom-button {
  line-height: 2.2rem !important;
  padding: 15px 17px !important;
  font-size: 1.8rem !important;
  min-width: 179px;
}
.product-info-main .product-info-stock-sku {
  padding-bottom: 0px;
}
@media (max-width: 575.98px) {
  .tocart, .custom-button {
    width: 100% !important;
  }
  .contact-seller {
    margin-bottom: 1em;
  }
}
</style>
