#!/usr/bin/env bash

# Grant correct permissions to all web files
sudo chmod -R 674 /var/www/html

# Grant write permissions to cache files
sudo chmod -R 677 /var/www/html/var

# Remove execute permissions from all files
sudo chmod -R -x+X * /var/www/html

# Make the Magento command line tool executable
sudo chmod u+x /var/www/html/bin/magento

# Grant execute permissions to all scripts
sudo chmod +x /var/www/html/scripts/*

# Grant all permissions to potato compressor cache folders
sudo chmod -R 777 /var/www/html/var/cache /var/www/html/var/tmp /var/www/html/var/page_cache /var/www/html/pub/static

# Grant all permissions to the tmp directory
sudo chmod -R 777 /var/www/html/pub/media/tmp /var/www/html/pub/media/catalog
