<?php
/**
 * Google Maps location template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
  $latitude = $block->getProduct()->getCustomAttribute('latitude')->getValue();
  $longitude = $block->getProduct()->getCustomAttribute('longitude')->getValue();
  if($latitude == null || $longitude == null) exit;
?>
<div style="display: flex">
  <iframe width="600" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=<?= $latitude ?>%2C%20<?= $longitude ?>&key=AIzaSyBn-qn2lVWPma_DYxAbA5_0W4NhmdaH0u8" allowfullscreen></iframe>
</div>
