<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$model =  \Magento\Framework\App\ObjectManager::getInstance();
$productSku = $block->getProduct()->getSku();
$VendorProduct = $model->create('Ced\CsMarketplace\Model\Vproducts')->getCollection()->addFieldToFilter('sku',$productSku)->addFieldToFilter('check_status',['nin'=>3])->getFirstItem();
$sessionId = $model->create('Magento\Customer\Model\Session')->getVendorId();
$VendorId = $VendorProduct->getVendorId();

if (!empty($VendorId) && $sessionId != $VendorId) {
	$array = array('name');
	$vendorModel = $model->create('Ced\CsMarketplace\Model\Vendor')->getCollection()->addAttributeToSelect(array('public_name'))->addAttributeToFilter('entity_id',$VendorId)->toArray();
	$shopUrl = $model->create('Ced\CsMarketplace\Model\Vendor')->load($VendorId)->getVendorShopUrl();
	$vendorModel = current($vendorModel);
	$public_name = $vendorModel['public_name'];?>
	<div class="vendor-info">
		<div class="row">
			<div class="col-md-6 listedBy">
				<?php echo __('Listed by: ');?><a href=<?php echo $shopUrl;?>><?php echo $public_name; ?></a>
			</div>
			<div class="col-md-6">
				<a target="_blank" href="https://stripe.com/about"><img width="44%" src="/pub/media/logo/default/powered_by_stripe.png" /></a>
			</div>
		</div>
	</div>
<?php
}
?>
<style>
.vendor-info {
    margin-bottom: 8px;
    margin-top: 4px;
}
.product-info-main .product-info-price {
	margin-bottom: 0px
}
.listedBy {
	margin-top: 0.5em;
}
</style>
