<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View
 */
?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.1&appId=459353637836730&autoLogAppEvents=1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$model =  \Magento\Framework\App\ObjectManager::getInstance();
$productSku = $block->getProduct()->getSku();
$VendorProduct = $model->create('Ced\CsMarketplace\Model\Vproducts')->getCollection()->addFieldToFilter('sku',$productSku)->addFieldToFilter('check_status',['nin'=>3])->getFirstItem();
$sessionId = $model->create('Magento\Customer\Model\Session')->getVendorId();
$VendorId = $VendorProduct->getVendorId();
$userProduct = $sessionId == $VendorId;
$latitude = $_product->getCustomAttribute('latitude');

// get vendor rating
$review_data = $model->create('Ced\CsVendorReview\Model\Review')->getCollection()->addFieldToFilter('vendor_id', $VendorId)->addFieldToFilter('status', 1);
$rating_data = $model->create('Ced\CsVendorReview\Model\Rating')->getCollection()->addFieldToSelect('rating_code');

$count = 0;
$rating_sum = 0;

// get vendor products
$vendor_products = $model->create('Ced\CsMarketplace\Model\Vproducts')->getCollection()
    ->addFieldToFilter('vendor_id', $VendorId)
    ->addFieldToFilter('check_status', 1)
    ->addFieldToSelect('product_id');

if (count($vendor_products)>0) {
    $ratingFactory = $model->create('Magento\Review\Model\Rating');
    foreach ($vendor_products as $product) {
        $rating = $ratingFactory->getEntitySummary($product['product_id']);
        if ($rating->getSum()!=null) {
            $rating_sum+=($rating->getSum()/$rating->getCount());
        }
    }
}

foreach ($review_data as $key => $value) {
    foreach ($rating_data as $k => $val) {
        if ($value[$val['rating_code']] > 0) {
            $rating_sum += $value[$val['rating_code']];
            $count++;
        }
    }
}

if ($count > 0 && $rating_sum > 0) {
    $width = $rating_sum/$count;
    $width = ceil($width);
} else {
    $width = 0;
}

$array = array('name');
$vendorModel = $model->create('Ced\CsMarketplace\Model\Vendor')->getCollection()->addAttributeToSelect(array('public_name'))->addAttributeToFilter('entity_id',$VendorId)->toArray();
$shopUrl = $model->create('Ced\CsMarketplace\Model\Vendor')->load($VendorId)->getVendorShopUrl();
$vendorModel = current($vendorModel);
$public_name = $vendorModel['public_name'];
$name_parts = explode(' ', $public_name);

if($public_name != null && isset($name_parts[0])){
  if($width == 0){
    $title = $name_parts[0] . ' has not sold any items yet.';
  }else{
    $title = 'View '.  $name_parts[0] . '\'s Reviews';
  }
}

?>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<script>
require(['jquery'], ($) => {

  $(document).ready(() => {
    window.twttr = (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0],
      t = window.twttr || {};
    if (d.getElementById(id)) return t;
    js = d.createElement(s);
    js.id = id;
    js.src = "https://platform.twitter.com/widgets.js";
    fjs.parentNode.insertBefore(js, fjs);

    t._e = [];
    t.ready = function(f) {
      t._e.push(f);
    };

    return t;
    }(document, "script", "twitter-wjs"));

    // social media buttons
    $('.price-container').append(`

<?php
  if($userProduct && $latitude != null){
?>
			<div class="row">
				<div class="col-xs-1" style="padding-left: 0;" id="social1"></div>
				<div class="col-xs-1" style="padding-left: 0;" id="social6"></div>
        <div class="col-xs-7" style="float: right; padding-left: 1.9em; padding-right: 0.6em; margin-top: -2em;" id="social3">
          <a id="craigslist-link" target="_blank" href="https://post.craigslist.org">Post on craigslist</a>
        </div>
      </div>
<?php
  }
?>
			<div class="row">
				<div class="col-xs-5" style="padding-left: 0;" id="social1"></div>
				<div class="col-xs-1" style="padding-left: 0;" id="social6"></div>
        <div class="col-xs-1" style="padding-left: 3.4em; padding-right: 0.2em;" id="social3">
          <div style="margin-bottom: 0.2em; float: right; padding-left: 0;" class="fb-share-button" data-href="<?= "https://resold.us/".$_SERVER['PHP_SELF'].$_SERVER['REQUEST_URI'] ?>" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>
        </div>
  			<div class="col-xs-1" style="padding-left: 0;" id="social7">
          <a class="twitter-share-button"
            href="https://twitter.com/intent/tweet"
            data-size="medium">
            Tweet</a>
  			</div>
        <div class="col-xs-3 stripe-container" style="display: none" id="social5">
        	<a target="_blank" href="https://stripe.com/about"><img class="powered_by_stripe" width="100%;" src="/pub/media/logo/default/powered_by_stripe.png" /></a>
        </div>
        <div class="col-xs-1" style="padding-left: 1.2em;" id="social2">
          <i title="Copy to Clipboard" style="cursor: pointer;" onclick="copyToClipboard()" class="fas fa-copy"></i>
        </div>
      </div>
			<div class="row">
				<div class="col-xs-5" id="social4">
					<strong class="listedBy"><a href="<?php echo str_replace('.html', '', $shopUrl);?>"><?php echo "Listed by: &nbsp;".$public_name; ?></a></strong><br/>
          <a href="/csvendorreview/rating/lists/id/<?= $VendorId ?>/">
            <div class="rating-summary">
               <div title="<?php echo $title ?>" class="rating-result">
                 <span style="width:<?php echo $width ?>%;"><span><?php echo $width ?>%</span></span>
               </div>
            </div>
          </a>
				</div>
				<div class="col-xs-4 stripe-container">
						<a target="_blank" href="https://stripe.com/about"><img class="powered_by_stripe" width="85%;" src="/pub/media/logo/default/powered_by_stripe.png" /></a>
				</div>
			</div>`);
  });

  $(document).on('click', '#craigslist-link', function() {
    copyToClipboard(true);
    return false;
  });
});

const copyToClipboard = (redirect) => {
  const el = document.createElement('textarea');
  el.value = 'https://<?= $_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'] ?>';
  document.body.appendChild(el);
  el.select();
  document.execCommand('copy');
  document.body.removeChild(el);
  if(redirect){
    alert("You will be redirected to craigslist to post your item. Please include the copied Resold URL in your craigslist post to allow online payment.");
    window.open('https://post.craigslist.org');
  }else{
    alert("Successfully copied link to clipboard.");
  }
};
</script>
<style>
.col-xs-1, .col-sm-1, .col-md-1, .col-lg-1, .col-xs-2, .col-sm-2, .col-md-2, .col-lg-2, .col-xs-3, .col-sm-3, .col-md-3, .col-lg-3, .col-xs-4, .col-sm-4, .col-md-4, .col-lg-4, .col-sm-5, .col-md-5, .col-lg-5, .col-xs-6, .col-sm-6, .col-md-6, .col-lg-6, .col-xs-7, .col-sm-7, .col-md-7, .col-lg-7, .col-xs-8, .col-sm-8, .col-md-8, .col-lg-8, .col-xs-9, .col-sm-9, .col-md-9, .col-lg-9, .col-xs-10, .col-sm-10, .col-md-10, .col-lg-10, .col-xs-11, .col-sm-11, .col-md-11, .col-lg-11, .col-xs-12, .col-sm-12, .col-md-12, .col-lg-12 {
  padding-left: 0;
}
.rating-result {
  margin-left: -0.5em !important;
}
.maindiv-social {
	display: none;
}
.vendor-info {
    margin-bottom: 8px;
    margin-top: 4px;
		display:flex;
}
.product-info-main .product-info-price {
	margin-bottom: 0px
}
.powered_by_stripe {
	margin-left: 5.5em;
	float: right;
}
@media (min-width: 575.98px) {
  #social4 {
    margin-top: -0.9em;
  }
}
@media (max-width: 575.98px) {
  #craigslist-link {
    margin-left: -2em;
  }
  .stripe-container {
    display: none;
		margin-left: 2.3em;
  }
  #social1 {
    float: right;
  }
  #social2 {
    padding-left: 0em !important;
    margin-top: 0.2em;
  }
  #social3 {
    margin-left: 2.25em;
    padding-left: 3.6em !important;
    margin-top: 0.25em;
  }
  #social4 {
    margin-top: 0.2em;
    width: 100%;
  }
  #social5 {
    display: block !important;
    width: 5.55em !important;
    padding-right: 0.3em;
    margin-top: 0.2em;
  }
  #social6 {
    display: none;
  }
  #social7 {
    margin-top: 0.25em;
  }
}
</style>
